[package]
name = "sentinext"
version = "0.3.6"
description = "SentiNext desktop shell"
authors = ["SentiNext"]
edition = "2021"
build = "build.rs"

[dependencies]
tauri = { version = "1.5", features = ["custom-protocol"] }
serde = { version = "1", features = ["derive"] }
keyring = "2.3"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
