"use client";

import { motion } from "framer-motion";
import { CornerMarkers } from "@/components/ui/corner-markers";

export function TermsClient({ dict, lang }: { dict: any, lang: string }) {
    return (
        <div className="flex flex-col min-h-screen items-center w-full">
            <section className="py-20 md:py-32 bg-transparent relative overflow-hidden flex flex-col items-center justify-center border-b border-[#00F0FF]/10 w-full">
                <div className="scanline" />
                <div className="container px-4 md:px-6 text-center max-w-5xl mx-auto relative z-10">
                    <motion.h1
                        initial={{ opacity: 0, scale: 0.95 }}
                        animate={{ opacity: 1, scale: 1 }}
                        transition={{ duration: 0.8 }}
                        className="text-6xl md:text-8xl lg:text-9xl font-bold tracking-tighter mb-8 leading-tight uppercase"
                    >
                        {lang === 'it' ? 'Termini' : 'Usage'} <span className="text-[#00F0FF] shadow-[#00F0FF]/50 drop-shadow-[0_0_15px_rgba(0,240,255,0.3)]">{lang === 'it' ? 'Servizio.' : 'Terms.'}</span>
                    </motion.h1>
                    <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mx-auto mb-10 font-mono uppercase tracking-[0.2em] opacity-60">
                        {lang === 'it' ? 'Protocolli di stretta di mano per i servizi SentiNext.' : 'Handshake protocols for SentiNext services.'}
                    </p>
                </div>
            </section>

            <section className="py-24 w-full flex justify-center relative">
                <div className="container px-4 md:px-6 mx-auto relative z-10 text-foreground/80 font-mono text-sm uppercase tracking-wide leading-relaxed">
                    <div className="max-w-4xl mx-auto p-12 rounded-sm border border-[#00F0FF]/10 bg-black/40 backdrop-blur-xl relative space-y-12">
                        <CornerMarkers />

                        <div>
                            <h2 className="text-[#00F0FF] text-xl font-bold mb-4">{lang === 'it' ? '1. Protocollo Beta' : '1. Beta Protocol'}</h2>
                            <p>{lang === 'it'
                                ? 'SentiNext è attualmente in Beta Pubblica. La piattaforma viene fornita "così com\'è" senza SLA garantiti per l\'uptime. Ci riserviamo il diritto di modificare le quote di telemetria in qualsiasi momento per garantire la stabilità del sistema.'
                                : 'SentiNext is currently in Public Beta. The platform is provided "as is" with no guaranteed uptime SLA. We reserve the right to modify telemetry quotas at any time to ensure system stability.'}</p>
                        </div>

                        <div>
                            <h2 className="text-[#00F0FF] text-xl font-bold mb-4">{lang === 'it' ? '2. Distribuzione Agenti' : '2. Agent Deployment'}</h2>
                            <p>{lang === 'it'
                                ? 'È possibile distribuire agenti di analisi solo per gli AppID Steam per i quali si ha un legittimo interesse analitico. I crawler automatizzati che tentano di aggirare i nostri limiti di frequenza saranno messi in quarantena.'
                                : 'You may only deploy analysis agents for Steam AppIDs for which you have a legitimate analytical interest. Automated scrapers attempting to bypass our rate limits will be quarantined.'}</p>
                        </div>

                        <div>
                            <h2 className="text-[#00F0FF] text-xl font-bold mb-4">{lang === 'it' ? '3. Proprietà dei Dati' : '3. Data Ownership'}</h2>
                            <p>{lang === 'it'
                                ? 'Gli insight dell\'analisi generati dall\'LLM SentiNext rimangono di tua proprietà. Tuttavia, il testo pubblico delle recensioni Steam ingerito rimane soggetto ai termini di servizio originali di Valve Corporation.'
                                : 'Analysis insights generated by the SentiNext LLM remains your property. However, public Steam review text ingested remains subject to Valve Corporation\'s original terms of service.'}</p>
                        </div>

                        <div>
                            <h2 className="text-[#00F0FF] text-xl font-bold mb-4">{lang === 'it' ? '4. Responsabilità' : '4. Liability'}</h2>
                            <p>{lang === 'it'
                                ? 'SentiNext non è responsabile per decisioni aziendali prese sulla base della telemetria classificata dall\'AI. L\'AI può allucinare; si raccomanda sempre la verifica manuale delle citazioni di evidenza.'
                                : 'SentiNext is not responsible for business decisions made based on AI-classified telemetry. AI can hallucinate; manual verification of evidence quotes is always recommended.'}</p>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}
