'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'it' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat with Agent',
    'nav.chatMobile': 'Agent',
    'nav.compare': 'Compare',
    'nav.database': 'Database',
    'nav.reports': 'Reports',
    'nav.support': 'Support',
    'nav.inbox': 'Inbox',
    'nav.settings': 'Settings',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.calculate': 'Calculate',
    'common.refresh': 'Refresh',
    'common.clearFilters': 'Clear filters',
    'common.pending': 'Pending',
    'common.dismiss': 'Dismiss',
    'common.reviews': 'Reviews',
    'common.games': 'Games',
    'common.languages': 'Languages',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.recommended': 'Recommended',
    'common.notRecommended': 'Not recommended',
    'common.issues': 'Issues',
    'common.requests': 'Requests',
    'common.evidence': 'Evidence',
    'common.labels': 'Labels',
    'common.noData': 'No data',

    // Filters
    'filters.allSentiment': 'All sentiment',
    'filters.allTime': 'All time',
    'filters.last30Days': 'Last 30 days',
    'filters.last90Days': 'Last 90 days',
    'filters.last12Months': 'Last 12 months',
    'filters.customRange': 'Custom range',
    'filters.allHelpful': 'All helpful',
    'filters.helpfulVotes10': '10+ votes',
    'filters.helpfulVotes25': '25+ votes',
    'filters.helpfulVotes50': '50+ votes',
    'filters.allPlaytime': 'All playtime',
    'filters.playtimeLt2h': '<2h playtime',
    'filters.playtime2to20h': '2–20h playtime',
    'filters.playtime20hplus': '20h+ playtime',
    'filters.helpfulVotes': '{count}+ helpful',
    'filters.languageChip': 'Lang: {lang}',

    // Game Context
    'gameContext.currentGame': 'Current game',
    'gameContext.noGame': 'No game',
    'gameContext.noSavedGames': 'No saved games',
    'gameContext.analyzeNew': 'Analyze new game',
    'gameContext.filteredReviews': 'Filtered reviews: {filtered} / {total}',
    'gameContext.sampledReviews': 'Sampled reviews: {total}',
    'gameContext.filtersApply': 'Filters apply to your current game reviews.',
    'gameContext.selectGameHint': 'Select a game to see review totals.',
    'gameContext.analyzeToSeeReviews': 'Analyze this game to see review totals.',
    'gameContext.activeFilters': 'Active filters:',
    'gameContext.noFiltersActive': 'No filters active',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.analyze': 'Analyze',
    'dashboard.update': 'Update',
    'dashboard.analyzing': 'Analyzing...',
    'dashboard.noGames': 'No games analyzed yet',
    'dashboard.recommendation': 'Recommendation',
    'dashboard.issueRate': 'Issue rate',
    'dashboard.requestRate': 'Request rate',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcomeTo': 'Welcome to SENTINEXT',
    'dashboard.subtitle': 'Understand what players really think. Start with a new Steam analysis or jump back into a recent report.',
    'dashboard.newAnalysis': 'New game analysis',
    'dashboard.newAnalysisDesc': 'Search Steam to begin a fresh review classification run.',
    'dashboard.searchPlaceholder': 'Search for a game (e.g., Baldur\'s Gate 3)',
    'dashboard.searching': 'Searching...',
    'dashboard.noGamesFound': 'No games found. Try a different search term.',
    'dashboard.recentAnalyses': 'Recent analyses',
    'dashboard.recentDesc': 'Open a saved dashboard from your latest runs.',
    'dashboard.viewAll': 'View all',
    'dashboard.noAnalyses': 'No analyses yet',
    'dashboard.noAnalysesDesc': 'Search for a game to start your first analysis.',
    'dashboard.openReviews': 'Open reviews',
    'dashboard.filtersActive': 'Active',
    'dashboard.showFilters': 'Show all filters',
    'dashboard.hideFilters': 'Hide all filters',
    'dashboard.lastMonthOnly': 'Last 30 days',
    'dashboard.categoriesOverview': 'Categories overview',
    'dashboard.topIssues': 'Top issues',
    'dashboard.topRequests': 'Top feature requests',
    'dashboard.newSearch': 'New Search',
    'dashboard.settings': 'Settings',
    'dashboard.costPreview': 'Cost Preview',
    'dashboard.calculating': 'Calculating...',
    'dashboard.costPreviewHint': 'Click Calculate to preview credits, cache reuse, and ETA.',
    'dashboard.processing': 'Processing',
    'dashboard.newReviews': 'New reviews',
    'dashboard.cached': 'Cached',
    'dashboard.cacheReuse': 'Cache reuse',
    'dashboard.etaRough': 'ETA (rough)',
    'dashboard.llmCalls': 'LLM calls',
    'dashboard.creditsLabel': 'Credits',
    'dashboard.costLabel': 'Cost',
    'dashboard.balanceLabel': 'Balance',
    'dashboard.creditStatusInsufficient': 'Insufficient',
    'dashboard.creditStatusOverLimit': 'Over limit',
    'dashboard.creditStatusOk': 'OK',
    'dashboard.creditWarningHard': 'Insufficient credits. Upgrade your plan or reduce reviews.',
    'dashboard.creditWarningSoft': 'This will exceed your monthly limit but you can still proceed.',
    'dashboard.queueRunning': 'Analysis running • {count} in queue',
    'dashboard.queueStatus': 'Queue: {count} running',

    // Chat
    'chat.title': 'Chat with Agent',
    'chat.subtitle': 'Your intelligent conversation partner',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.newChat': 'New Chat',
    'chat.history': 'Chat History',
    'chat.context': 'Context',
    'chat.noConversations': 'No conversations yet',
    'chat.selectGames': 'Select up to 2 games to search reviews:',
    'chat.clearSelection': 'Clear selection',
    'chat.noStarredGames': 'No starred games yet',
    'chat.loadingGames': 'Loading games...',
    'chat.chatWithData': 'Chat with Your Data',
    'chat.startConversation': 'Start a conversation',
    'chat.askAnything': 'Ask me anything!',
    'chat.sources': 'Sources',
    'chat.sourcesUsed': 'Sources used',
    'chat.showSources': 'Show sources',
    'chat.hideSources': 'Hide sources',
    'chat.promptPresets': 'Prompt presets',
    'chat.selectGameNotice': 'Select a game to run this prompt.',
    'chat.copySuccess': 'Answer copied',
    'chat.copyFailed': 'Copy failed',
    'chat.copy': 'Copy',
    'chat.regenerate': 'Regenerate',
    'chat.suggestedQuestions': 'Suggested questions',
    'chat.pleaseClarify': 'Please clarify',
    'chat.selectGame': 'Select a game',
    'chat.searchFor': 'Search for {game}',
    'chat.searchForGames': 'Search for games',
    'chat.loadingConversation': 'Loading conversation...',

    // Compare
    'compare.title': 'Game Comparison',
    'compare.selectGames': 'Select at least 2 games',
    'compare.categoryOverview': 'Category Overview',
    'compare.categoryRecommendation': 'Category recommendation',
    'compare.sortBy': 'Sort by:',
    'compare.biggestDiff': 'Biggest Difference',
    'compare.highestRating': 'Highest Rating',
    'compare.lowestRating': 'Lowest Rating',
    'compare.mostReviews': 'Most Reviews',
    'compare.onlySignificant': 'Only show significant differences (>10%)',
    'compare.resetFilters': 'Reset filters',
    'compare.sampleReviews': 'Sample Reviews',
    'compare.exampleReviews': 'Example reviews from each game for this subcategory',
    'compare.noGames': 'No games to compare',
    'compare.analyzeFirst': 'Analyze some games first to compare them here.',
    'compare.selectGamesDesc': 'Select Games',
    'compare.selected': 'Selected',
    'compare.visual Comparison': 'Visual comparison across all categories',
    'compare.swapPrompt': 'Only 2 games can be compared. Swap in {game}?',
    'compare.swapHint': 'Choose a game to replace.',
    'compare.swapReplace': 'Replace {game}',

    // Database
    'database.title': 'Database Explorer',
    'database.subtitle': 'Browse every stored review across all accounts.',
    'database.myData': 'My data',
    'database.allUsers': 'All users',
    'database.stats': 'Database statistics',
    'database.loadingStats': 'Loading stats...',
    'database.games': 'Games',
    'database.reviews': 'Reviews',
    'database.starred': 'Starred',
    'database.labels': 'Labels',
    'database.noData': 'No local data yet',
    'database.noDataDesc': 'Run your first analysis to populate the database.',
    'database.filters': 'Dataset filters',
    'database.filtersDesc': 'Search and filter across the entire database.',
    'database.searchText': 'Search text',
    'database.searchPlaceholder': 'Search review text',
    'database.game': 'Game',
    'database.allGames': 'All games',
    'database.language': 'Language',
    'database.category': 'Category',
    'database.allCategories': 'All categories',
    'database.subcategory': 'Subcategory',
    'database.allSubcategories': 'All subcategories',
    'database.quickFilters': 'Quick filters',
    'database.allSentiment': 'All sentiment',
    'database.allLabels': 'All labels',
    'database.downloadCSV': 'Download CSV',
    'database.downloadJSON': 'Download JSONL',
    'database.noReviews': 'No reviews match these filters.',
    'database.reviewDetails': 'Review details',
    'database.categories': 'Categories',
    'database.metadata': 'Metadata',
    'database.export': 'Export',
    'database.sentiment': 'Sentiment',
    'database.type': 'Type',
    'database.previewExport': 'Preview export',
    'database.preparingExport': 'Preparing…',
    'database.applyFilters': 'Apply filters',
    'database.scope': 'Scope',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Account, storage, and diagnostics for this service.',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select your preferred language',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.account': 'Account',
    'settings.accountDesc': 'Manage your session and sign out.',
    'settings.diagnostics': 'Diagnostics',
    'settings.diagnosticsDesc': 'Use this when the backend is slow or unresponsive.',
    'settings.recheckBackend': 'Recheck backend',
    'settings.refreshLogs': 'Refresh logs',
    'settings.copyDiagnostics': 'Copy diagnostics',
    'settings.copied': 'Copied.',
    'settings.backendStatus': 'Backend status:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'checking',
    'settings.appVersion': 'App version',

    // Languages
    'lang.en': 'English',
    'lang.it': 'Italian',
    'lang.fr': 'French',
    'lang.de': 'German',

    // Onboarding
    'onboarding.welcome': 'Welcome to SENTINEXT',
    'onboarding.welcomeDesc': 'Understand what players really think about any Steam game with AI-powered review analysis.',
    'onboarding.step1.title': 'Search & Analyze',
    'onboarding.step1.desc': 'Search for any Steam game and analyze up to 1,000 reviews with our AI classification system.',
    'onboarding.step2.title': 'Insights Dashboard',
    'onboarding.step2.desc': 'Get KPIs, sentiment trends, player segmentation, and category breakdowns at a glance.',
    'onboarding.step3.title': 'AI-Powered Features',
    'onboarding.step3.desc': 'Chat with an AI agent, generate summaries, and compare games side by side.',
    'onboarding.skip': 'Skip',
    'onboarding.back': 'Back',
    'onboarding.next': 'Next',
    'onboarding.getStarted': 'Get Started',
    'onboarding.feature.chat': 'Chat Agent',
    'onboarding.feature.chatDesc': 'Ask questions about player feedback',
    'onboarding.feature.summary': 'AI Summaries',
    'onboarding.feature.summaryDesc': 'Get instant insights from reviews',
    'onboarding.feature.compare': 'Compare Games',
    'onboarding.feature.compareDesc': 'Benchmark against competitors',

    // Onboarding - stat labels
    'onboarding.stat.reviewsAnalyzed': 'Reviews Analyzed',
    'onboarding.stat.aiCategories': 'AI Categories',
    'onboarding.stat.languages': 'Languages',

    // Onboarding - Step 2 section headers
    'onboarding.step2.keyMetrics': 'Key Metrics',
    'onboarding.step2.sentimentTrend': 'Sentiment Trend',
    'onboarding.step2.categoryBreakdown': 'Category Breakdown',

    // Onboarding - Step 4 (Pricing)
    'onboarding.step4.title': 'Plans & Pricing',
    'onboarding.step4.desc': 'Start free and scale as you grow. Every plan includes AI classification, chat, and summaries.',

    // Onboarding - Tier labels
    'onboarding.tier.free': 'Free',
    'onboarding.tier.indie': 'Indie',
    'onboarding.tier.pro': 'Pro',
    'onboarding.tier.enterprise': 'Enterprise',
    'onboarding.tier.perMonth': 'mo',
    'onboarding.tier.custom': 'Custom',
    'onboarding.tier.unlimited': 'Unlimited',
    'onboarding.tier.popular': 'Popular',
    'onboarding.tier.creditsLabel': 'Credits',
    'onboarding.tier.trialCredits': '1,000 trial',
    'onboarding.tier.indieCredits': '5,000/mo',
    'onboarding.tier.proCredits': '15,000/mo',
    'onboarding.tier.creditCosts': 'Credit Costs',
    'onboarding.tier.classifyCost': 'Classify: 1 credit',
    'onboarding.tier.chatCost': 'Chat: 2 credits',
    'onboarding.tier.summaryCost': 'Summary: 1 credit',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Cruscotto',
    'nav.chat': 'Chat con Agente',
    'nav.chatMobile': 'Agente',
    'nav.compare': 'Confronta',
    'nav.database': 'Database',
    'nav.reports': 'Rapporti',
    'nav.support': 'Supporto',
    'nav.inbox': 'Inbox',
    'nav.settings': 'Impostazioni',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.reset': 'Reimposta',
    'common.apply': 'Applica',
    'common.calculate': 'Calcola',
    'common.refresh': 'Aggiorna',
    'common.clearFilters': 'Cancella filtri',
    'common.pending': 'In sospeso',
    'common.dismiss': 'Chiudi',
    'common.reviews': 'Recensioni',
    'common.games': 'Giochi',
    'common.languages': 'Lingue',
    'common.filters': 'Filtri',
    'common.all': 'Tutti',
    'common.recommended': 'Raccomandato',
    'common.notRecommended': 'Non raccomandato',
    'common.issues': 'Problemi',
    'common.requests': 'Richieste',
    'common.evidence': 'Evidenze',
    'common.labels': 'Etichette',
    'common.noData': 'Nessun dato',

    // Filters
    'filters.allSentiment': 'Tutti i sentimenti',
    'filters.allTime': 'Sempre',
    'filters.last30Days': 'Ultimi 30 giorni',
    'filters.last90Days': 'Ultimi 90 giorni',
    'filters.last12Months': 'Ultimi 12 mesi',
    'filters.customRange': 'Intervallo personalizzato',
    'filters.allHelpful': 'Tutte le valutazioni',
    'filters.helpfulVotes10': '10+ voti',
    'filters.helpfulVotes25': '25+ voti',
    'filters.helpfulVotes50': '50+ voti',
    'filters.allPlaytime': 'Tutte le ore di gioco',
    'filters.playtimeLt2h': '<2h di gioco',
    'filters.playtime2to20h': '2–20h di gioco',
    'filters.playtime20hplus': '20h+ di gioco',
    'filters.helpfulVotes': '{count}+ utili',
    'filters.languageChip': 'Lingua: {lang}',

    // Game Context
    'gameContext.currentGame': 'Gioco attuale',
    'gameContext.noGame': 'Nessun gioco',
    'gameContext.noSavedGames': 'Nessun gioco salvato',
    'gameContext.analyzeNew': 'Analizza un nuovo gioco',
    'gameContext.filteredReviews': 'Recensioni filtrate: {filtered} / {total}',
    'gameContext.sampledReviews': 'Recensioni campionate: {total}',
    'gameContext.filtersApply': 'I filtri si applicano alle recensioni del gioco selezionato.',
    'gameContext.selectGameHint': 'Seleziona un gioco per vedere il totale recensioni.',
    'gameContext.analyzeToSeeReviews': 'Analizza questo gioco per vedere il totale recensioni.',
    'gameContext.activeFilters': 'Filtri attivi:',
    'gameContext.noFiltersActive': 'Nessun filtro attivo',

    // Dashboard
    'dashboard.title': 'Cruscotto',
    'dashboard.analyze': 'Analizza',
    'dashboard.update': 'Aggiorna',
    'dashboard.analyzing': 'Analizzando...',
    'dashboard.noGames': 'Nessun gioco analizzato',
    'dashboard.recommendation': 'Raccomandazione',
    'dashboard.issueRate': 'Tasso problemi',
    'dashboard.requestRate': 'Tasso richieste',
    'dashboard.welcome': 'Benvenuto',
    'dashboard.welcomeTo': 'Benvenuto su SENTINEXT',
    'dashboard.subtitle': 'Comprendi cosa pensano veramente i giocatori. Inizia una nuova analisi Steam o torna a un report recente.',
    'dashboard.newAnalysis': 'Nuova analisi gioco',
    'dashboard.newAnalysisDesc': 'Cerca su Steam per iniziare una nuova classificazione recensioni.',
    'dashboard.searchPlaceholder': 'Cerca un gioco (es. Baldur\'s Gate 3)',
    'dashboard.searching': 'Ricerca...',
    'dashboard.noGamesFound': 'Nessun gioco trovato. Prova con un altro termine.',
    'dashboard.recentAnalyses': 'Analisi recenti',
    'dashboard.recentDesc': 'Apri un cruscotto salvato dalle tue ultime esecuzioni.',
    'dashboard.viewAll': 'Vedi tutto',
    'dashboard.noAnalyses': 'Nessuna analisi',
    'dashboard.noAnalysesDesc': 'Cerca un gioco per iniziare la tua prima analisi.',
    'dashboard.openReviews': 'Apri recensioni',
    'dashboard.filtersActive': 'Attivi',
    'dashboard.showFilters': 'Mostra tutti i filtri',
    'dashboard.hideFilters': 'Nascondi tutti i filtri',
    'dashboard.lastMonthOnly': 'Ultimi 30 giorni',
    'dashboard.categoriesOverview': 'Panoramica categorie',
    'dashboard.topIssues': 'Principali problemi',
    'dashboard.topRequests': 'Principali richieste',
    'dashboard.newSearch': 'Nuova Ricerca',
    'dashboard.settings': 'Impostazioni',
    'dashboard.costPreview': 'Anteprima costi',
    'dashboard.calculating': 'Calcolo...',
    'dashboard.costPreviewHint': 'Clicca Calcola per vedere crediti, riuso cache ed ETA.',
    'dashboard.processing': 'Elaborazione',
    'dashboard.newReviews': 'Nuove recensioni',
    'dashboard.cached': 'In cache',
    'dashboard.cacheReuse': 'Riuso cache',
    'dashboard.etaRough': 'ETA (stimata)',
    'dashboard.llmCalls': 'Chiamate LLM',
    'dashboard.creditsLabel': 'Crediti',
    'dashboard.costLabel': 'Costo',
    'dashboard.balanceLabel': 'Saldo',
    'dashboard.creditStatusInsufficient': 'Insufficiente',
    'dashboard.creditStatusOverLimit': 'Oltre limite',
    'dashboard.creditStatusOk': 'OK',
    'dashboard.creditWarningHard': 'Crediti insufficienti. Aggiorna il piano o riduci le recensioni.',
    'dashboard.creditWarningSoft': 'Supererà il limite mensile ma puoi procedere.',
    'dashboard.queueRunning': 'Analisi in corso • {count} in coda',
    'dashboard.queueStatus': 'Coda: {count} in esecuzione',

    // Chat
    'chat.title': 'Chat con Agente',
    'chat.subtitle': 'Il tuo partner conversazionale intelligente',
    'chat.placeholder': 'Scrivi il tuo messaggio...',
    'chat.send': 'Invia',
    'chat.newChat': 'Nuova Chat',
    'chat.history': 'Cronologia Chat',
    'chat.context': 'Contesto',
    'chat.noConversations': 'Nessuna conversazione',
    'chat.selectGames': 'Seleziona fino a 2 giochi per cercare recensioni:',
    'chat.clearSelection': 'Cancella selezione',
    'chat.noStarredGames': 'Nessun gioco preferito',
    'chat.loadingGames': 'Caricamento giochi...',
    'chat.chatWithData': 'Chat con i Tuoi Dati',
    'chat.startConversation': 'Inizia una conversazione',
    'chat.askAnything': 'Chiedimi qualsiasi cosa!',
    'chat.sources': 'Fonti',
    'chat.sourcesUsed': 'Fonti usate',
    'chat.showSources': 'Mostra fonti',
    'chat.hideSources': 'Nascondi fonti',
    'chat.promptPresets': 'Prompt predefiniti',
    'chat.selectGameNotice': 'Seleziona un gioco per usare questo prompt.',
    'chat.copySuccess': 'Risposta copiata',
    'chat.copyFailed': 'Copia non riuscita',
    'chat.copy': 'Copia',
    'chat.regenerate': 'Rigenera',
    'chat.suggestedQuestions': 'Domande suggerite',
    'chat.pleaseClarify': 'Per favore chiarisci',
    'chat.selectGame': 'Seleziona un gioco',
    'chat.searchFor': 'Cerca {game}',
    'chat.searchForGames': 'Cerca giochi',
    'chat.loadingConversation': 'Caricamento conversazione...',

    // Compare
    'compare.title': 'Confronto Giochi',
    'compare.selectGames': 'Seleziona almeno 2 giochi',
    'compare.categoryOverview': 'Panoramica Categorie',
    'compare.categoryRecommendation': 'Raccomandazione per categoria',
    'compare.sortBy': 'Ordina per:',
    'compare.biggestDiff': 'Differenza Maggiore',
    'compare.highestRating': 'Valutazione Più Alta',
    'compare.lowestRating': 'Valutazione Più Bassa',
    'compare.mostReviews': 'Più Recensioni',
    'compare.onlySignificant': 'Mostra solo differenze significative (>10%)',
    'compare.resetFilters': 'Reimposta filtri',
    'compare.sampleReviews': 'Recensioni di Esempio',
    'compare.exampleReviews': 'Esempi di recensioni da ogni gioco per questa sottocategoria',
    'compare.noGames': 'Nessun gioco da confrontare',
    'compare.analyzeFirst': 'Analizza prima alcuni giochi per confrontarli qui.',
    'compare.selectGamesDesc': 'Seleziona Giochi',
    'compare.selected': 'Selezionati',
    'compare.visualComparison': 'Confronto visivo tra tutte le categorie',
    'compare.swapPrompt': 'Si possono confrontare solo 2 giochi. Sostituire con {game}?',
    'compare.swapHint': 'Scegli un gioco da sostituire.',
    'compare.swapReplace': 'Sostituisci {game}',

    // Database
    'database.title': 'Esploratore Database',
    'database.subtitle': 'Sfoglia tutte le recensioni archiviate.',
    'database.myData': 'I miei dati',
    'database.allUsers': 'Tutti gli utenti',
    'database.stats': 'Statistiche database',
    'database.loadingStats': 'Caricamento statistiche...',
    'database.games': 'Giochi',
    'database.reviews': 'Recensioni',
    'database.starred': 'Preferiti',
    'database.labels': 'Etichette',
    'database.noData': 'Nessun dato locale',
    'database.noDataDesc': 'Esegui la tua prima analisi per popolare il database.',
    'database.filters': 'Filtri dataset',
    'database.filtersDesc': 'Cerca e filtra nell\'intero database.',
    'database.searchText': 'Cerca testo',
    'database.searchPlaceholder': 'Cerca testo recensione',
    'database.game': 'Gioco',
    'database.allGames': 'Tutti i giochi',
    'database.language': 'Lingua',
    'database.category': 'Categoria',
    'database.allCategories': 'Tutte le categorie',
    'database.subcategory': 'Sottocategoria',
    'database.allSubcategories': 'Tutte le sottocategorie',
    'database.quickFilters': 'Filtri rapidi',
    'database.allSentiment': 'Tutti i sentimenti',
    'database.allLabels': 'Tutte le etichette',
    'database.downloadCSV': 'Scarica CSV',
    'database.downloadJSON': 'Scarica JSONL',
    'database.noReviews': 'Nessuna recensione corrisponde ai filtri.',
    'database.reviewDetails': 'Dettagli recensione',
    'database.categories': 'Categorie',
    'database.metadata': 'Metadati',
    'database.export': 'Esporta',
    'database.sentiment': 'Sentimento',
    'database.type': 'Tipo',
    'database.previewExport': 'Anteprima export',
    'database.preparingExport': 'Preparazione…',
    'database.applyFilters': 'Applica filtri',
    'database.scope': 'Ambito',

    // Settings
    'settings.title': 'Impostazioni',
    'settings.subtitle': 'Account, archiviazione e diagnostica per questo servizio.',
    'settings.language': 'Lingua',
    'settings.selectLanguage': 'Seleziona la tua lingua preferita',
    'settings.appearance': 'Aspetto',
    'settings.notifications': 'Notifiche',
    'settings.account': 'Account',
    'settings.accountDesc': 'Gestisci la tua sessione e disconnettiti.',
    'settings.diagnostics': 'Diagnostica',
    'settings.diagnosticsDesc': 'Usa quando il backend è lento o non risponde.',
    'settings.recheckBackend': 'Ricontrolla backend',
    'settings.refreshLogs': 'Aggiorna log',
    'settings.copyDiagnostics': 'Copia diagnostica',
    'settings.copied': 'Copiato.',
    'settings.backendStatus': 'Stato backend:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'controllo',
    'settings.appVersion': 'Versione app',

    // Languages
    'lang.en': 'Inglese',
    'lang.it': 'Italiano',
    'lang.fr': 'Francese',
    'lang.de': 'Tedesco',

    // Onboarding
    'onboarding.welcome': 'Benvenuto in SENTINEXT',
    'onboarding.welcomeDesc': 'Scopri cosa pensano davvero i giocatori di qualsiasi gioco Steam con l\'analisi delle recensioni basata sull\'IA.',
    'onboarding.step1.title': 'Cerca e Analizza',
    'onboarding.step1.desc': 'Cerca qualsiasi gioco Steam e analizza fino a 1.000 recensioni con il nostro sistema di classificazione IA.',
    'onboarding.step2.title': 'Dashboard Insights',
    'onboarding.step2.desc': 'Ottieni KPI, tendenze del sentiment, segmentazione dei giocatori e analisi delle categorie a colpo d\'occhio.',
    'onboarding.step3.title': 'Funzionalità IA',
    'onboarding.step3.desc': 'Chatta con un agente IA, genera riassunti e confronta i giochi fianco a fianco.',
    'onboarding.skip': 'Salta',
    'onboarding.back': 'Indietro',
    'onboarding.next': 'Avanti',
    'onboarding.getStarted': 'Inizia',
    'onboarding.feature.chat': 'Agente Chat',
    'onboarding.feature.chatDesc': 'Fai domande sul feedback dei giocatori',
    'onboarding.feature.summary': 'Riassunti IA',
    'onboarding.feature.summaryDesc': 'Ottieni insights istantanei dalle recensioni',
    'onboarding.feature.compare': 'Confronta Giochi',
    'onboarding.feature.compareDesc': 'Benchmark contro i concorrenti',

    // Onboarding - stat labels
    'onboarding.stat.reviewsAnalyzed': 'Recensioni Analizzate',
    'onboarding.stat.aiCategories': 'Categorie IA',
    'onboarding.stat.languages': 'Lingue',

    // Onboarding - Step 2 section headers
    'onboarding.step2.keyMetrics': 'Metriche Chiave',
    'onboarding.step2.sentimentTrend': 'Tendenza Sentiment',
    'onboarding.step2.categoryBreakdown': 'Analisi Categorie',

    // Onboarding - Step 4 (Pricing)
    'onboarding.step4.title': 'Piani e Prezzi',
    'onboarding.step4.desc': 'Inizia gratis e scala man mano che cresci. Ogni piano include classificazione IA, chat e riassunti.',

    // Onboarding - Tier labels
    'onboarding.tier.free': 'Gratuito',
    'onboarding.tier.indie': 'Indie',
    'onboarding.tier.pro': 'Pro',
    'onboarding.tier.enterprise': 'Enterprise',
    'onboarding.tier.perMonth': 'mese',
    'onboarding.tier.custom': 'Personalizzato',
    'onboarding.tier.unlimited': 'Illimitati',
    'onboarding.tier.popular': 'Popolare',
    'onboarding.tier.creditsLabel': 'Crediti',
    'onboarding.tier.trialCredits': '1.000 prova',
    'onboarding.tier.indieCredits': '5.000/mese',
    'onboarding.tier.proCredits': '15.000/mese',
    'onboarding.tier.creditCosts': 'Costi Crediti',
    'onboarding.tier.classifyCost': 'Classifica: 1 credito',
    'onboarding.tier.chatCost': 'Chat: 2 crediti',
    'onboarding.tier.summaryCost': 'Riassunto: 1 credito',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.chat': 'Chat avec agent',
    'nav.chatMobile': 'Agent',
    'nav.compare': 'Comparer',
    'nav.database': 'Base de données',
    'nav.reports': 'Rapports',
    'nav.support': 'Support',
    'nav.inbox': 'Inbox',
    'nav.settings': 'Paramètres',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.reset': 'Réinitialiser',
    'common.apply': 'Appliquer',
    'common.calculate': 'Calculer',
    'common.refresh': 'Actualiser',
    'common.clearFilters': 'Effacer les filtres',
    'common.pending': 'En attente',
    'common.dismiss': 'Fermer',
    'common.reviews': 'Avis',
    'common.games': 'Jeux',
    'common.languages': 'Langues',
    'common.filters': 'Filtres',
    'common.all': 'Tous',
    'common.recommended': 'Recommandé',
    'common.notRecommended': 'Non recommandé',
    'common.issues': 'Problèmes',
    'common.requests': 'Demandes',
    'common.evidence': 'Preuves',
    'common.labels': 'Étiquettes',
    'common.noData': 'Aucune donnée',

    // Filters
    'filters.allSentiment': 'Tous les sentiments',
    'filters.allTime': 'Tout le temps',
    'filters.last30Days': '30 derniers jours',
    'filters.last90Days': '90 derniers jours',
    'filters.last12Months': '12 derniers mois',
    'filters.customRange': 'Plage personnalisée',
    'filters.allHelpful': 'Tous les votes utiles',
    'filters.helpfulVotes10': '10+ votes',
    'filters.helpfulVotes25': '25+ votes',
    'filters.helpfulVotes50': '50+ votes',
    'filters.allPlaytime': 'Tout temps de jeu',
    'filters.playtimeLt2h': '<2h de jeu',
    'filters.playtime2to20h': '2–20h de jeu',
    'filters.playtime20hplus': '20h+ de jeu',
    'filters.helpfulVotes': '{count}+ utiles',
    'filters.languageChip': 'Langue : {lang}',

    // Game Context
    'gameContext.currentGame': 'Jeu actuel',
    'gameContext.noGame': 'Aucun jeu',
    'gameContext.noSavedGames': 'Aucun jeu sauvegardé',
    'gameContext.analyzeNew': 'Analyser un nouveau jeu',
    'gameContext.filteredReviews': 'Avis filtrés : {filtered} / {total}',
    'gameContext.sampledReviews': 'Avis échantillonnés : {total}',
    'gameContext.filtersApply': 'Les filtres s\'appliquent aux avis du jeu sélectionné.',
    'gameContext.selectGameHint': 'Sélectionnez un jeu pour voir le total des avis.',
    'gameContext.analyzeToSeeReviews': 'Analysez ce jeu pour voir le total des avis.',
    'gameContext.activeFilters': 'Filtres actifs :',
    'gameContext.noFiltersActive': 'Aucun filtre actif',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.analyze': 'Analyser',
    'dashboard.update': 'Mettre à jour',
    'dashboard.analyzing': 'Analyse...',
    'dashboard.noGames': 'Aucun jeu analysé',
    'dashboard.recommendation': 'Recommandation',
    'dashboard.issueRate': 'Taux de problèmes',
    'dashboard.requestRate': 'Taux de demandes',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.welcomeTo': 'Bienvenue sur SENTINEXT',
    'dashboard.subtitle': 'Comprenez ce que les joueurs pensent vraiment. Commencez une nouvelle analyse Steam ou revenez à un rapport récent.',
    'dashboard.newAnalysis': 'Nouvelle analyse de jeu',
    'dashboard.newAnalysisDesc': 'Recherchez Steam pour commencer une nouvelle classification d\'avis.',
    'dashboard.searchPlaceholder': 'Rechercher un jeu (ex. Baldur\'s Gate 3)',
    'dashboard.searching': 'Recherche...',
    'dashboard.noGamesFound': 'Aucun jeu trouvé. Essayez un autre terme.',
    'dashboard.recentAnalyses': 'Analyses récentes',
    'dashboard.recentDesc': 'Ouvrez un tableau de bord sauvegardé de vos dernières exécutions.',
    'dashboard.viewAll': 'Tout voir',
    'dashboard.noAnalyses': 'Aucune analyse',
    'dashboard.noAnalysesDesc': 'Recherchez un jeu pour commencer votre première analyse.',
    'dashboard.openReviews': 'Ouvrir les avis',
    'dashboard.filtersActive': 'Actifs',
    'dashboard.showFilters': 'Afficher tous les filtres',
    'dashboard.hideFilters': 'Masquer tous les filtres',
    'dashboard.lastMonthOnly': '30 derniers jours',
    'dashboard.categoriesOverview': 'Aperçu des catégories',
    'dashboard.topIssues': 'Principaux problèmes',
    'dashboard.topRequests': 'Principales demandes',
    'dashboard.newSearch': 'Nouvelle Recherche',
    'dashboard.settings': 'Paramètres',
    'dashboard.costPreview': 'Aperçu des coûts',
    'dashboard.calculating': 'Calcul en cours...',
    'dashboard.costPreviewHint': 'Cliquez sur Calculer pour voir crédits, cache et ETA.',
    'dashboard.processing': 'Traitement',
    'dashboard.newReviews': 'Nouveaux avis',
    'dashboard.cached': 'En cache',
    'dashboard.cacheReuse': 'Réutilisation cache',
    'dashboard.etaRough': 'ETA (approx.)',
    'dashboard.llmCalls': 'Appels LLM',
    'dashboard.creditsLabel': 'Crédits',
    'dashboard.costLabel': 'Coût',
    'dashboard.balanceLabel': 'Solde',
    'dashboard.creditStatusInsufficient': 'Insuffisant',
    'dashboard.creditStatusOverLimit': 'Dépassement',
    'dashboard.creditStatusOk': 'OK',
    'dashboard.creditWarningHard': 'Crédits insuffisants. Mettez à niveau ou réduisez les avis.',
    'dashboard.creditWarningSoft': 'Dépassement de la limite mensuelle, mais vous pouvez continuer.',
    'dashboard.queueRunning': 'Analyse en cours • {count} en file',
    'dashboard.queueStatus': 'File : {count} en cours',

    // Chat
    'chat.title': 'Chat avec agent',
    'chat.subtitle': 'Votre partenaire conversationnel intelligent',
    'chat.placeholder': 'Tapez votre message...',
    'chat.send': 'Envoyer',
    'chat.newChat': 'Nouveau Chat',
    'chat.history': 'Historique des chats',
    'chat.context': 'Contexte',
    'chat.noConversations': 'Aucune conversation',
    'chat.selectGames': 'Sélectionnez jusqu\'à 2 jeux pour rechercher des avis:',
    'chat.clearSelection': 'Effacer la sélection',
    'chat.noStarredGames': 'Aucun jeu favori',
    'chat.loadingGames': 'Chargement des jeux...',
    'chat.chatWithData': 'Discuter avec Vos Données',
    'chat.startConversation': 'Démarrer une conversation',
    'chat.askAnything': 'Demandez-moi n\'importe quoi!',
    'chat.sources': 'Sources',
    'chat.sourcesUsed': 'Sources utilisées',
    'chat.showSources': 'Afficher les sources',
    'chat.hideSources': 'Masquer les sources',
    'chat.promptPresets': 'Prompts prédéfinis',
    'chat.selectGameNotice': 'Sélectionnez un jeu pour exécuter ce prompt.',
    'chat.copySuccess': 'Réponse copiée',
    'chat.copyFailed': 'Échec de la copie',
    'chat.copy': 'Copier',
    'chat.regenerate': 'Regénérer',
    'chat.suggestedQuestions': 'Questions suggérées',
    'chat.pleaseClarify': 'Veuillez préciser',
    'chat.selectGame': 'Sélectionner un jeu',
    'chat.searchFor': 'Rechercher {game}',
    'chat.searchForGames': 'Rechercher des jeux',
    'chat.loadingConversation': 'Chargement de la conversation...',

    // Compare
    'compare.title': 'Comparaison de jeux',
    'compare.selectGames': 'Sélectionnez au moins 2 jeux',
    'compare.categoryOverview': 'Aperçu des catégories',
    'compare.categoryRecommendation': 'Recommandation par catégorie',
    'compare.sortBy': 'Trier par:',
    'compare.biggestDiff': 'Plus grande différence',
    'compare.highestRating': 'Note la plus élevée',
    'compare.lowestRating': 'Note la plus basse',
    'compare.mostReviews': 'Plus d\'avis',
    'compare.onlySignificant': 'Afficher uniquement les différences significatives (>10%)',
    'compare.resetFilters': 'Réinitialiser les filtres',
    'compare.sampleReviews': 'Exemples d\'avis',
    'compare.exampleReviews': 'Exemples d\'avis de chaque jeu pour cette sous-catégorie',
    'compare.noGames': 'Aucun jeu à comparer',
    'compare.analyzeFirst': 'Analysez d\'abord des jeux pour les comparer ici.',
    'compare.selectGamesDesc': 'Sélectionner des jeux',
    'compare.selected': 'Sélectionnés',
    'compare.visualComparison': 'Comparaison visuelle de toutes les catégories',
    'compare.swapPrompt': 'Seuls 2 jeux peuvent être comparés. Remplacer par {game} ?',
    'compare.swapHint': 'Choisissez un jeu à remplacer.',
    'compare.swapReplace': 'Remplacer {game}',

    // Database
    'database.title': 'Explorateur de base de données',
    'database.subtitle': 'Parcourez tous les avis stockés.',
    'database.myData': 'Mes données',
    'database.allUsers': 'Tous les utilisateurs',
    'database.stats': 'Statistiques de la base de données',
    'database.loadingStats': 'Chargement des statistiques...',
    'database.games': 'Jeux',
    'database.reviews': 'Avis',
    'database.starred': 'Favoris',
    'database.labels': 'Étiquettes',
    'database.noData': 'Aucune donnée locale',
    'database.noDataDesc': 'Effectuez votre première analyse pour remplir la base de données.',
    'database.filters': 'Filtres de dataset',
    'database.filtersDesc': 'Rechercher et filtrer dans toute la base de données.',
    'database.searchText': 'Rechercher du texte',
    'database.searchPlaceholder': 'Rechercher le texte d\'avis',
    'database.game': 'Jeu',
    'database.allGames': 'Tous les jeux',
    'database.language': 'Langue',
    'database.category': 'Catégorie',
    'database.allCategories': 'Toutes les catégories',
    'database.subcategory': 'Sous-catégorie',
    'database.allSubcategories': 'Toutes les sous-catégories',
    'database.quickFilters': 'Filtres rapides',
    'database.allSentiment': 'Tous les sentiments',
    'database.allLabels': 'Toutes les étiquettes',
    'database.downloadCSV': 'Télécharger CSV',
    'database.downloadJSON': 'Télécharger JSONL',
    'database.noReviews': 'Aucun avis ne correspond à ces filtres.',
    'database.reviewDetails': 'Détails de l\'avis',
    'database.categories': 'Catégories',
    'database.metadata': 'Métadonnées',
    'database.export': 'Exporter',
    'database.sentiment': 'Sentiment',
    'database.type': 'Type',
    'database.previewExport': 'Aperçu de l’export',
    'database.preparingExport': 'Préparation…',
    'database.applyFilters': 'Appliquer les filtres',
    'database.scope': 'Portée',

    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Compte, stockage et diagnostics pour ce service.',
    'settings.language': 'Langue',
    'settings.selectLanguage': 'Sélectionnez votre langue préférée',
    'settings.appearance': 'Apparence',
    'settings.notifications': 'Notifications',
    'settings.account': 'Compte',
    'settings.accountDesc': 'Gérez votre session et déconnectez-vous.',
    'settings.diagnostics': 'Diagnostics',
    'settings.diagnosticsDesc': 'Utilisez ceci lorsque le backend est lent ou ne répond pas.',
    'settings.recheckBackend': 'Revérifier le backend',
    'settings.refreshLogs': 'Actualiser les journaux',
    'settings.copyDiagnostics': 'Copier les diagnostics',
    'settings.copied': 'Copié.',
    'settings.backendStatus': 'État du backend:',
    'settings.online': 'en ligne',
    'settings.offline': 'hors ligne',
    'settings.checking': 'vérification',
    'settings.appVersion': 'Version de l\'app',

    // Languages
    'lang.en': 'Anglais',
    'lang.it': 'Italien',
    'lang.fr': 'Français',
    'lang.de': 'Allemand',

    // Onboarding
    'onboarding.welcome': 'Bienvenue sur SENTINEXT',
    'onboarding.welcomeDesc': 'Comprenez ce que les joueurs pensent vraiment de n\'importe quel jeu Steam grâce à l\'analyse des avis par IA.',
    'onboarding.step1.title': 'Rechercher et Analyser',
    'onboarding.step1.desc': 'Recherchez n\'importe quel jeu Steam et analysez jusqu\'à 1 000 avis avec notre système de classification IA.',
    'onboarding.step2.title': 'Tableau de Bord',
    'onboarding.step2.desc': 'Obtenez des KPI, des tendances de sentiment, une segmentation des joueurs et une analyse des catégories en un coup d\'œil.',
    'onboarding.step3.title': 'Fonctionnalités IA',
    'onboarding.step3.desc': 'Discutez avec un agent IA, générez des résumés et comparez les jeux côte à côte.',
    'onboarding.skip': 'Passer',
    'onboarding.back': 'Retour',
    'onboarding.next': 'Suivant',
    'onboarding.getStarted': 'Commencer',
    'onboarding.feature.chat': 'Agent Chat',
    'onboarding.feature.chatDesc': 'Posez des questions sur les retours des joueurs',
    'onboarding.feature.summary': 'Résumés IA',
    'onboarding.feature.summaryDesc': 'Obtenez des insights instantanés des avis',
    'onboarding.feature.compare': 'Comparer les Jeux',
    'onboarding.feature.compareDesc': 'Benchmark contre les concurrents',

    // Onboarding - stat labels
    'onboarding.stat.reviewsAnalyzed': 'Avis Analysés',
    'onboarding.stat.aiCategories': 'Catégories IA',
    'onboarding.stat.languages': 'Langues',

    // Onboarding - Step 2 section headers
    'onboarding.step2.keyMetrics': 'Métriques Clés',
    'onboarding.step2.sentimentTrend': 'Tendance du Sentiment',
    'onboarding.step2.categoryBreakdown': 'Répartition par Catégorie',

    // Onboarding - Step 4 (Pricing)
    'onboarding.step4.title': 'Plans et Tarifs',
    'onboarding.step4.desc': 'Commencez gratuitement et évoluez à votre rythme. Chaque plan inclut la classification IA, le chat et les résumés.',

    // Onboarding - Tier labels
    'onboarding.tier.free': 'Gratuit',
    'onboarding.tier.indie': 'Indie',
    'onboarding.tier.pro': 'Pro',
    'onboarding.tier.enterprise': 'Enterprise',
    'onboarding.tier.perMonth': 'mois',
    'onboarding.tier.custom': 'Sur mesure',
    'onboarding.tier.unlimited': 'Illimités',
    'onboarding.tier.popular': 'Populaire',
    'onboarding.tier.creditsLabel': 'Crédits',
    'onboarding.tier.trialCredits': '1 000 essai',
    'onboarding.tier.indieCredits': '5 000/mois',
    'onboarding.tier.proCredits': '15 000/mois',
    'onboarding.tier.creditCosts': 'Coûts des Crédits',
    'onboarding.tier.classifyCost': 'Classifier : 1 crédit',
    'onboarding.tier.chatCost': 'Chat : 2 crédits',
    'onboarding.tier.summaryCost': 'Résumé : 1 crédit',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat mit Agent',
    'nav.chatMobile': 'Agent',
    'nav.compare': 'Vergleichen',
    'nav.database': 'Datenbank',
    'nav.reports': 'Berichte',
    'nav.support': 'Support',
    'nav.inbox': 'Inbox',
    'nav.settings': 'Einstellungen',

    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.reset': 'Zurücksetzen',
    'common.apply': 'Anwenden',
    'common.calculate': 'Berechnen',
    'common.refresh': 'Aktualisieren',
    'common.clearFilters': 'Filter löschen',
    'common.pending': 'Ausstehend',
    'common.dismiss': 'Schließen',
    'common.reviews': 'Bewertungen',
    'common.games': 'Spiele',
    'common.languages': 'Sprachen',
    'common.filters': 'Filter',
    'common.all': 'Alle',
    'common.recommended': 'Empfohlen',
    'common.notRecommended': 'Nicht empfohlen',
    'common.issues': 'Probleme',
    'common.requests': 'Anfragen',
    'common.evidence': 'Beweise',
    'common.labels': 'Etiketten',
    'common.noData': 'Keine Daten',

    // Filters
    'filters.allSentiment': 'Alle Stimmungen',
    'filters.allTime': 'Gesamter Zeitraum',
    'filters.last30Days': 'Letzte 30 Tage',
    'filters.last90Days': 'Letzte 90 Tage',
    'filters.last12Months': 'Letzte 12 Monate',
    'filters.customRange': 'Benutzerdefinierter Bereich',
    'filters.allHelpful': 'Alle hilfreichen',
    'filters.helpfulVotes10': '10+ Stimmen',
    'filters.helpfulVotes25': '25+ Stimmen',
    'filters.helpfulVotes50': '50+ Stimmen',
    'filters.allPlaytime': 'Alle Spielzeiten',
    'filters.playtimeLt2h': '<2h Spielzeit',
    'filters.playtime2to20h': '2–20h Spielzeit',
    'filters.playtime20hplus': '20h+ Spielzeit',
    'filters.helpfulVotes': '{count}+ hilfreich',
    'filters.languageChip': 'Sprache: {lang}',

    // Game Context
    'gameContext.currentGame': 'Aktuelles Spiel',
    'gameContext.noGame': 'Kein Spiel',
    'gameContext.noSavedGames': 'Keine gespeicherten Spiele',
    'gameContext.analyzeNew': 'Neues Spiel analysieren',
    'gameContext.filteredReviews': 'Gefilterte Reviews: {filtered} / {total}',
    'gameContext.sampledReviews': 'Stichproben-Reviews: {total}',
    'gameContext.filtersApply': 'Filter gelten für die Reviews des aktuellen Spiels.',
    'gameContext.selectGameHint': 'Wähle ein Spiel, um die Review-Anzahl zu sehen.',
    'gameContext.analyzeToSeeReviews': 'Analysiere dieses Spiel, um die Review-Anzahl zu sehen.',
    'gameContext.activeFilters': 'Aktive Filter:',
    'gameContext.noFiltersActive': 'Keine aktiven Filter',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.analyze': 'Analysieren',
    'dashboard.update': 'Aktualisieren',
    'dashboard.analyzing': 'Analysiere...',
    'dashboard.noGames': 'Noch keine Spiele analysiert',
    'dashboard.recommendation': 'Empfehlung',
    'dashboard.issueRate': 'Problem-Rate',
    'dashboard.requestRate': 'Anfrage-Rate',
    'dashboard.welcome': 'Willkommen',
    'dashboard.welcomeTo': 'Willkommen bei SENTINEXT',
    'dashboard.subtitle': 'Verstehen Sie, was Spieler wirklich denken. Starten Sie eine neue Steam-Analyse oder kehren Sie zu einem kürzlichen Bericht zurück.',
    'dashboard.newAnalysis': 'Neue Spielanalyse',
    'dashboard.newAnalysisDesc': 'Suchen Sie auf Steam, um eine neue Bewertungsklassifizierung zu beginnen.',
    'dashboard.searchPlaceholder': 'Nach einem Spiel suchen (z.B. Baldur\'s Gate 3)',
    'dashboard.searching': 'Suche...',
    'dashboard.noGamesFound': 'Keine Spiele gefunden. Versuchen Sie einen anderen Suchbegriff.',
    'dashboard.recentAnalyses': 'Letzte Analysen',
    'dashboard.recentDesc': 'Öffnen Sie ein gespeichertes Dashboard aus Ihren letzten Läufen.',
    'dashboard.viewAll': 'Alle anzeigen',
    'dashboard.noAnalyses': 'Noch keine Analysen',
    'dashboard.noAnalysesDesc': 'Suchen Sie nach einem Spiel, um Ihre erste Analyse zu starten.',
    'dashboard.openReviews': 'Bewertungen öffnen',
    'dashboard.filtersActive': 'Aktiv',
    'dashboard.showFilters': 'Alle Filter anzeigen',
    'dashboard.hideFilters': 'Alle Filter ausblenden',
    'dashboard.lastMonthOnly': 'Letzte 30 Tage',
    'dashboard.categoriesOverview': 'Kategorieübersicht',
    'dashboard.topIssues': 'Hauptprobleme',
    'dashboard.topRequests': 'Hauptanfragen',
    'dashboard.newSearch': 'Neue Suche',
    'dashboard.settings': 'Einstellungen',
    'dashboard.costPreview': 'Kostenübersicht',
    'dashboard.calculating': 'Wird berechnet...',
    'dashboard.costPreviewHint': 'Klicke auf Berechnen, um Credits, Cache und ETA zu sehen.',
    'dashboard.processing': 'Verarbeitung',
    'dashboard.newReviews': 'Neue Reviews',
    'dashboard.cached': 'Im Cache',
    'dashboard.cacheReuse': 'Cache-Wiederverwendung',
    'dashboard.etaRough': 'ETA (grob)',
    'dashboard.llmCalls': 'LLM-Aufrufe',
    'dashboard.creditsLabel': 'Credits',
    'dashboard.costLabel': 'Kosten',
    'dashboard.balanceLabel': 'Guthaben',
    'dashboard.creditStatusInsufficient': 'Unzureichend',
    'dashboard.creditStatusOverLimit': 'Über Limit',
    'dashboard.creditStatusOk': 'OK',
    'dashboard.creditWarningHard': 'Nicht genügend Credits. Upgrade oder weniger Reviews.',
    'dashboard.creditWarningSoft': 'Monatslimit wird überschritten, du kannst trotzdem fortfahren.',
    'dashboard.queueRunning': 'Analyse läuft • {count} in der Warteschlange',
    'dashboard.queueStatus': 'Warteschlange: {count} läuft',

    // Chat
    'chat.title': 'Chat mit Agent',
    'chat.subtitle': 'Ihr intelligenter Gesprächspartner',
    'chat.placeholder': 'Geben Sie Ihre Nachricht ein...',
    'chat.send': 'Senden',
    'chat.newChat': 'Neuer Chat',
    'chat.history': 'Chat-Verlauf',
    'chat.context': 'Kontext',
    'chat.noConversations': 'Noch keine Gespräche',
    'chat.selectGames': 'Wählen Sie bis zu 2 Spiele aus, um Bewertungen zu durchsuchen:',
    'chat.clearSelection': 'Auswahl löschen',
    'chat.noStarredGames': 'Keine Lieblingsspiele',
    'chat.loadingGames': 'Spiele laden...',
    'chat.chatWithData': 'Mit Ihren Daten chatten',
    'chat.startConversation': 'Gespräch beginnen',
    'chat.askAnything': 'Fragen Sie mich alles!',
    'chat.sources': 'Quellen',
    'chat.sourcesUsed': 'Quellen verwendet',
    'chat.showSources': 'Quellen anzeigen',
    'chat.hideSources': 'Quellen verbergen',
    'chat.promptPresets': 'Prompt-Vorlagen',
    'chat.selectGameNotice': 'Wähle ein Spiel, um diesen Prompt auszuführen.',
    'chat.copySuccess': 'Antwort kopiert',
    'chat.copyFailed': 'Kopieren fehlgeschlagen',
    'chat.copy': 'Kopieren',
    'chat.regenerate': 'Neu generieren',
    'chat.suggestedQuestions': 'Vorgeschlagene Fragen',
    'chat.pleaseClarify': 'Bitte präzisieren',
    'chat.selectGame': 'Spiel auswählen',
    'chat.searchFor': 'Suche {game}',
    'chat.searchForGames': 'Spiele suchen',
    'chat.loadingConversation': 'Unterhaltung wird geladen...',

    // Compare
    'compare.title': 'Spielevergleich',
    'compare.selectGames': 'Wählen Sie mindestens 2 Spiele',
    'compare.categoryOverview': 'Kategorieübersicht',
    'compare.categoryRecommendation': 'Kategorieempfehlung',
    'compare.sortBy': 'Sortieren nach:',
    'compare.biggestDiff': 'Größter Unterschied',
    'compare.highestRating': 'Höchste Bewertung',
    'compare.lowestRating': 'Niedrigste Bewertung',
    'compare.mostReviews': 'Meiste Bewertungen',
    'compare.onlySignificant': 'Nur signifikante Unterschiede anzeigen (>10%)',
    'compare.resetFilters': 'Filter zurücksetzen',
    'compare.sampleReviews': 'Beispielbewertungen',
    'compare.exampleReviews': 'Beispielbewertungen von jedem Spiel für diese Unterkategorie',
    'compare.noGames': 'Keine Spiele zum Vergleichen',
    'compare.analyzeFirst': 'Analysieren Sie zuerst einige Spiele, um sie hier zu vergleichen.',
    'compare.selectGamesDesc': 'Spiele auswählen',
    'compare.selected': 'Ausgewählt',
    'compare.visualComparison': 'Visueller Vergleich aller Kategorien',
    'compare.swapPrompt': 'Es können nur 2 Spiele verglichen werden. {game} ersetzen?',
    'compare.swapHint': 'Wähle ein Spiel zum Ersetzen.',
    'compare.swapReplace': '{game} ersetzen',

    // Database
    'database.title': 'Datenbank-Explorer',
    'database.subtitle': 'Durchsuchen Sie alle gespeicherten Bewertungen.',
    'database.myData': 'Meine Daten',
    'database.allUsers': 'Alle Benutzer',
    'database.stats': 'Datenbankstatistiken',
    'database.loadingStats': 'Statistiken laden...',
    'database.games': 'Spiele',
    'database.reviews': 'Bewertungen',
    'database.starred': 'Favoriten',
    'database.labels': 'Etiketten',
    'database.noData': 'Keine lokalen Daten',
    'database.noDataDesc': 'Führen Sie Ihre erste Analyse durch, um die Datenbank zu füllen.',
    'database.filters': 'Dataset-Filter',
    'database.filtersDesc': 'Durchsuchen und filtern Sie die gesamte Datenbank.',
    'database.searchText': 'Text suchen',
    'database.searchPlaceholder': 'Bewertungstext suchen',
    'database.game': 'Spiel',
    'database.allGames': 'Alle Spiele',
    'database.language': 'Sprache',
    'database.category': 'Kategorie',
    'database.allCategories': 'Alle Kategorien',
    'database.subcategory': 'Unterkategorie',
    'database.allSubcategories': 'Alle Unterkategorien',
    'database.quickFilters': 'Schnellfilter',
    'database.allSentiment': 'Alle Stimmungen',
    'database.allLabels': 'Alle Etiketten',
    'database.downloadCSV': 'CSV herunterladen',
    'database.downloadJSON': 'JSONL herunterladen',
    'database.noReviews': 'Keine Bewertungen entsprechen diesen Filtern.',
    'database.reviewDetails': 'Bewertungsdetails',
    'database.categories': 'Kategorien',
    'database.metadata': 'Metadaten',
    'database.export': 'Exportieren',
    'database.sentiment': 'Stimmung',
    'database.type': 'Typ',
    'database.previewExport': 'Exportvorschau',
    'database.preparingExport': 'Wird vorbereitet…',
    'database.applyFilters': 'Filter anwenden',
    'database.scope': 'Bereich',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Konto, Speicher und Diagnose für diesen Dienst.',
    'settings.language': 'Sprache',
    'settings.selectLanguage': 'Wählen Sie Ihre bevorzugte Sprache',
    'settings.appearance': 'Erscheinungsbild',
    'settings.notifications': 'Benachrichtigungen',
    'settings.account': 'Konto',
    'settings.accountDesc': 'Verwalten Sie Ihre Sitzung und melden Sie sich ab.',
    'settings.diagnostics': 'Diagnose',
    'settings.diagnosticsDesc': 'Verwenden Sie dies, wenn das Backend langsam ist oder nicht reagiert.',
    'settings.recheckBackend': 'Backend erneut prüfen',
    'settings.refreshLogs': 'Protokolle aktualisieren',
    'settings.copyDiagnostics': 'Diagnose kopieren',
    'settings.copied': 'Kopiert.',
    'settings.backendStatus': 'Backend-Status:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'prüfen',
    'settings.appVersion': 'App-Version',

    // Languages
    'lang.en': 'Englisch',
    'lang.it': 'Italienisch',
    'lang.fr': 'Französisch',
    'lang.de': 'Deutsch',

    // Onboarding
    'onboarding.welcome': 'Willkommen bei SENTINEXT',
    'onboarding.welcomeDesc': 'Verstehen Sie, was Spieler wirklich über jedes Steam-Spiel denken, mit KI-gestützter Bewertungsanalyse.',
    'onboarding.step1.title': 'Suchen & Analysieren',
    'onboarding.step1.desc': 'Suchen Sie nach jedem Steam-Spiel und analysieren Sie bis zu 1.000 Bewertungen mit unserem KI-Klassifizierungssystem.',
    'onboarding.step2.title': 'Insights Dashboard',
    'onboarding.step2.desc': 'Erhalten Sie KPIs, Stimmungstrends, Spielersegmentierung und Kategorieanalysen auf einen Blick.',
    'onboarding.step3.title': 'KI-Funktionen',
    'onboarding.step3.desc': 'Chatten Sie mit einem KI-Agenten, generieren Sie Zusammenfassungen und vergleichen Sie Spiele nebeneinander.',
    'onboarding.skip': 'Überspringen',
    'onboarding.back': 'Zurück',
    'onboarding.next': 'Weiter',
    'onboarding.getStarted': 'Loslegen',
    'onboarding.feature.chat': 'Chat-Agent',
    'onboarding.feature.chatDesc': 'Fragen zum Spieler-Feedback stellen',
    'onboarding.feature.summary': 'KI-Zusammenfassungen',
    'onboarding.feature.summaryDesc': 'Sofortige Insights aus Bewertungen',
    'onboarding.feature.compare': 'Spiele vergleichen',
    'onboarding.feature.compareDesc': 'Benchmark gegen Wettbewerber',

    // Onboarding - stat labels
    'onboarding.stat.reviewsAnalyzed': 'Bewertungen analysiert',
    'onboarding.stat.aiCategories': 'KI-Kategorien',
    'onboarding.stat.languages': 'Sprachen',

    // Onboarding - Step 2 section headers
    'onboarding.step2.keyMetrics': 'Kennzahlen',
    'onboarding.step2.sentimentTrend': 'Stimmungstrend',
    'onboarding.step2.categoryBreakdown': 'Kategorieaufschlüsselung',

    // Onboarding - Step 4 (Pricing)
    'onboarding.step4.title': 'Pläne & Preise',
    'onboarding.step4.desc': 'Starten Sie kostenlos und skalieren Sie mit Ihrem Wachstum. Jeder Plan enthält KI-Klassifizierung, Chat und Zusammenfassungen.',

    // Onboarding - Tier labels
    'onboarding.tier.free': 'Kostenlos',
    'onboarding.tier.indie': 'Indie',
    'onboarding.tier.pro': 'Pro',
    'onboarding.tier.enterprise': 'Enterprise',
    'onboarding.tier.perMonth': 'Monat',
    'onboarding.tier.custom': 'Individuell',
    'onboarding.tier.unlimited': 'Unbegrenzt',
    'onboarding.tier.popular': 'Beliebt',
    'onboarding.tier.creditsLabel': 'Credits',
    'onboarding.tier.trialCredits': '1.000 Test',
    'onboarding.tier.indieCredits': '5.000/Monat',
    'onboarding.tier.proCredits': '15.000/Monat',
    'onboarding.tier.creditCosts': 'Credit-Kosten',
    'onboarding.tier.classifyCost': 'Klassifizieren: 1 Credit',
    'onboarding.tier.chatCost': 'Chat: 2 Credits',
    'onboarding.tier.summaryCost': 'Zusammenfassung: 1 Credit',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const saved = localStorage.getItem('senti-next-language') as Language;
    if (saved && ['en', 'it', 'fr', 'de'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('senti-next-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
