'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'it' | 'fr' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.compare': 'Compare',
    'nav.database': 'Database',
    'nav.reports': 'Reports',
    'nav.settings': 'Settings',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.reset': 'Reset',
    'common.reviews': 'Reviews',
    'common.games': 'Games',
    'common.filters': 'Filters',
    'common.all': 'All',
    'common.recommended': 'Recommended',
    'common.notRecommended': 'Not recommended',
    'common.issues': 'Issues',
    'common.requests': 'Requests',
    'common.evidence': 'Evidence',
    'common.labels': 'Labels',
    'common.noData': 'No data',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.analyze': 'Analyze',
    'dashboard.analyzing': 'Analyzing...',
    'dashboard.noGames': 'No games analyzed yet',
    'dashboard.recommendation': 'Recommendation',
    'dashboard.issueRate': 'Issue rate',
    'dashboard.requestRate': 'Request rate',
    'dashboard.welcome': 'Welcome',
    'dashboard.welcomeTo': 'Welcome to SentiNext',
    'dashboard.subtitle': 'Understand what players really think. Start with a new Steam analysis or jump back into a recent report.',
    'dashboard.newAnalysis': 'New game analysis',
    'dashboard.newAnalysisDesc': 'Search Steam to begin a fresh review classification run.',
    'dashboard.searchPlaceholder': 'Search for a game (e.g., Baldur\'s Gate 3)',
    'dashboard.searching': 'Searching...',
    'dashboard.noGamesFound': 'No games found. Try a different search term.',
    'dashboard.recentAnalyses': 'Recent analyses',
    'dashboard.recentDesc': 'Open a saved dashboard from your latest runs.',
    'dashboard.viewAll': 'View all',
    'dashboard.noAnalyses': 'No analyses yet',
    'dashboard.noAnalysesDesc': 'Search for a game to start your first analysis.',
    'dashboard.openReviews': 'Open reviews',
    'dashboard.filtersActive': 'Active',
    'dashboard.showFilters': 'Show filters',
    'dashboard.hideFilters': 'Hide filters',
    'dashboard.categoriesOverview': 'Categories overview',
    'dashboard.topIssues': 'Top issues',
    'dashboard.topRequests': 'Top feature requests',
    'dashboard.newSearch': 'New Search',

    // Chat
    'chat.title': 'AI Assistant',
    'chat.subtitle': 'Your intelligent conversation partner',
    'chat.placeholder': 'Type your message...',
    'chat.send': 'Send',
    'chat.newChat': 'New Chat',
    'chat.history': 'Chat History',
    'chat.context': 'Context',
    'chat.noConversations': 'No conversations yet',
    'chat.selectGames': 'Select up to 2 games to search reviews:',
    'chat.clearSelection': 'Clear selection',
    'chat.noStarredGames': 'No starred games yet',
    'chat.loadingGames': 'Loading games...',
    'chat.chatWithData': 'Chat with Your Data',
    'chat.startConversation': 'Start a conversation',
    'chat.askAnything': 'Ask me anything!',
    'chat.sources': 'Sources',

    // Compare
    'compare.title': 'Game Comparison',
    'compare.selectGames': 'Select at least 2 games',
    'compare.categoryOverview': 'Category Overview',
    'compare.categoryRecommendation': 'Category recommendation',
    'compare.sortBy': 'Sort by:',
    'compare.biggestDiff': 'Biggest Difference',
    'compare.highestRating': 'Highest Rating',
    'compare.lowestRating': 'Lowest Rating',
    'compare.mostReviews': 'Most Reviews',
    'compare.onlySignificant': 'Only show significant differences (>10%)',
    'compare.resetFilters': 'Reset filters',
    'compare.sampleReviews': 'Sample Reviews',
    'compare.exampleReviews': 'Example reviews from each game for this subcategory',
    'compare.noGames': 'No games to compare',
    'compare.analyzeFirst': 'Analyze some games first to compare them here.',
    'compare.selectGamesDesc': 'Select Games',
    'compare.selected': 'Selected',
    'compare.visual Comparison': 'Visual comparison across all categories',

    // Database
    'database.title': 'Database Explorer',
    'database.subtitle': 'Browse every stored review across all accounts.',
    'database.myData': 'My data',
    'database.allUsers': 'All users',
    'database.stats': 'Database statistics',
    'database.loadingStats': 'Loading stats...',
    'database.games': 'Games',
    'database.reviews': 'Reviews',
    'database.starred': 'Starred',
    'database.labels': 'Labels',
    'database.noData': 'No local data yet',
    'database.noDataDesc': 'Run your first analysis to populate the database.',
    'database.filters': 'Dataset filters',
    'database.filtersDesc': 'Search and filter across the entire database.',
    'database.searchText': 'Search text',
    'database.searchPlaceholder': 'Search review text',
    'database.game': 'Game',
    'database.allGames': 'All games',
    'database.language': 'Language',
    'database.category': 'Category',
    'database.allCategories': 'All categories',
    'database.subcategory': 'Subcategory',
    'database.allSubcategories': 'All subcategories',
    'database.quickFilters': 'Quick filters',
    'database.allSentiment': 'All sentiment',
    'database.allLabels': 'All labels',
    'database.downloadCSV': 'Download CSV',
    'database.downloadJSON': 'Download JSONL',
    'database.noReviews': 'No reviews match these filters.',
    'database.reviewDetails': 'Review details',

    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Account, storage, and diagnostics for this service.',
    'settings.language': 'Language',
    'settings.selectLanguage': 'Select your preferred language',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.account': 'Account',
    'settings.accountDesc': 'Manage your session and sign out.',
    'settings.diagnostics': 'Diagnostics',
    'settings.diagnosticsDesc': 'Use this when the backend is slow or unresponsive.',
    'settings.recheckBackend': 'Recheck backend',
    'settings.refreshLogs': 'Refresh logs',
    'settings.copyDiagnostics': 'Copy diagnostics',
    'settings.copied': 'Copied.',
    'settings.backendStatus': 'Backend status:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'checking',
    'settings.appVersion': 'App version',

    // Languages
    'lang.en': 'English',
    'lang.it': 'Italian',
    'lang.fr': 'French',
    'lang.de': 'German',
  },
  it: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Cruscotto',
    'nav.chat': 'Chat',
    'nav.compare': 'Confronta',
    'nav.database': 'Database',
    'nav.reports': 'Rapporti',
    'nav.settings': 'Impostazioni',

    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.close': 'Chiudi',
    'common.search': 'Cerca',
    'common.filter': 'Filtra',
    'common.sort': 'Ordina',
    'common.reset': 'Reimposta',
    'common.reviews': 'Recensioni',
    'common.games': 'Giochi',
    'common.filters': 'Filtri',
    'common.all': 'Tutti',
    'common.recommended': 'Raccomandato',
    'common.notRecommended': 'Non raccomandato',
    'common.issues': 'Problemi',
    'common.requests': 'Richieste',
    'common.evidence': 'Evidenze',
    'common.labels': 'Etichette',
    'common.noData': 'Nessun dato',

    // Dashboard
    'dashboard.title': 'Cruscotto',
    'dashboard.analyze': 'Analizza',
    'dashboard.analyzing': 'Analizzando...',
    'dashboard.noGames': 'Nessun gioco analizzato',
    'dashboard.recommendation': 'Raccomandazione',
    'dashboard.issueRate': 'Tasso problemi',
    'dashboard.requestRate': 'Tasso richieste',
    'dashboard.welcome': 'Benvenuto',
    'dashboard.welcomeTo': 'Benvenuto su SentiNext',
    'dashboard.subtitle': 'Comprendi cosa pensano veramente i giocatori. Inizia una nuova analisi Steam o torna a un report recente.',
    'dashboard.newAnalysis': 'Nuova analisi gioco',
    'dashboard.newAnalysisDesc': 'Cerca su Steam per iniziare una nuova classificazione recensioni.',
    'dashboard.searchPlaceholder': 'Cerca un gioco (es. Baldur\'s Gate 3)',
    'dashboard.searching': 'Ricerca...',
    'dashboard.noGamesFound': 'Nessun gioco trovato. Prova con un altro termine.',
    'dashboard.recentAnalyses': 'Analisi recenti',
    'dashboard.recentDesc': 'Apri un cruscotto salvato dalle tue ultime esecuzioni.',
    'dashboard.viewAll': 'Vedi tutto',
    'dashboard.noAnalyses': 'Nessuna analisi',
    'dashboard.noAnalysesDesc': 'Cerca un gioco per iniziare la tua prima analisi.',
    'dashboard.openReviews': 'Apri recensioni',
    'dashboard.filtersActive': 'Attivi',
    'dashboard.showFilters': 'Mostra filtri',
    'dashboard.hideFilters': 'Nascondi filtri',
    'dashboard.categoriesOverview': 'Panoramica categorie',
    'dashboard.topIssues': 'Principali problemi',
    'dashboard.topRequests': 'Principali richieste',
    'dashboard.newSearch': 'Nuova Ricerca',

    // Chat
    'chat.title': 'Assistente AI',
    'chat.subtitle': 'Il tuo partner conversazionale intelligente',
    'chat.placeholder': 'Scrivi il tuo messaggio...',
    'chat.send': 'Invia',
    'chat.newChat': 'Nuova Chat',
    'chat.history': 'Cronologia Chat',
    'chat.context': 'Contesto',
    'chat.noConversations': 'Nessuna conversazione',
    'chat.selectGames': 'Seleziona fino a 2 giochi per cercare recensioni:',
    'chat.clearSelection': 'Cancella selezione',
    'chat.noStarredGames': 'Nessun gioco preferito',
    'chat.loadingGames': 'Caricamento giochi...',
    'chat.chatWithData': 'Chat con i Tuoi Dati',
    'chat.startConversation': 'Inizia una conversazione',
    'chat.askAnything': 'Chiedimi qualsiasi cosa!',
    'chat.sources': 'Fonti',

    // Compare
    'compare.title': 'Confronto Giochi',
    'compare.selectGames': 'Seleziona almeno 2 giochi',
    'compare.categoryOverview': 'Panoramica Categorie',
    'compare.categoryRecommendation': 'Raccomandazione per categoria',
    'compare.sortBy': 'Ordina per:',
    'compare.biggestDiff': 'Differenza Maggiore',
    'compare.highestRating': 'Valutazione Più Alta',
    'compare.lowestRating': 'Valutazione Più Bassa',
    'compare.mostReviews': 'Più Recensioni',
    'compare.onlySignificant': 'Mostra solo differenze significative (>10%)',
    'compare.resetFilters': 'Reimposta filtri',
    'compare.sampleReviews': 'Recensioni di Esempio',
    'compare.exampleReviews': 'Esempi di recensioni da ogni gioco per questa sottocategoria',
    'compare.noGames': 'Nessun gioco da confrontare',
    'compare.analyzeFirst': 'Analizza prima alcuni giochi per confrontarli qui.',
    'compare.selectGamesDesc': 'Seleziona Giochi',
    'compare.selected': 'Selezionati',
    'compare.visualComparison': 'Confronto visivo tra tutte le categorie',

    // Database
    'database.title': 'Esploratore Database',
    'database.subtitle': 'Sfoglia tutte le recensioni archiviate.',
    'database.myData': 'I miei dati',
    'database.allUsers': 'Tutti gli utenti',
    'database.stats': 'Statistiche database',
    'database.loadingStats': 'Caricamento statistiche...',
    'database.games': 'Giochi',
    'database.reviews': 'Recensioni',
    'database.starred': 'Preferiti',
    'database.labels': 'Etichette',
    'database.noData': 'Nessun dato locale',
    'database.noDataDesc': 'Esegui la tua prima analisi per popolare il database.',
    'database.filters': 'Filtri dataset',
    'database.filtersDesc': 'Cerca e filtra nell\'intero database.',
    'database.searchText': 'Cerca testo',
    'database.searchPlaceholder': 'Cerca testo recensione',
    'database.game': 'Gioco',
    'database.allGames': 'Tutti i giochi',
    'database.language': 'Lingua',
    'database.category': 'Categoria',
    'database.allCategories': 'Tutte le categorie',
    'database.subcategory': 'Sottocategoria',
    'database.allSubcategories': 'Tutte le sottocategorie',
    'database.quickFilters': 'Filtri rapidi',
    'database.allSentiment': 'Tutti i sentimenti',
    'database.allLabels': 'Tutte le etichette',
    'database.downloadCSV': 'Scarica CSV',
    'database.downloadJSON': 'Scarica JSONL',
    'database.noReviews': 'Nessuna recensione corrisponde ai filtri.',
    'database.reviewDetails': 'Dettagli recensione',

    // Settings
    'settings.title': 'Impostazioni',
    'settings.subtitle': 'Account, archiviazione e diagnostica per questo servizio.',
    'settings.language': 'Lingua',
    'settings.selectLanguage': 'Seleziona la tua lingua preferita',
    'settings.appearance': 'Aspetto',
    'settings.notifications': 'Notifiche',
    'settings.account': 'Account',
    'settings.accountDesc': 'Gestisci la tua sessione e disconnettiti.',
    'settings.diagnostics': 'Diagnostica',
    'settings.diagnosticsDesc': 'Usa quando il backend è lento o non risponde.',
    'settings.recheckBackend': 'Ricontrolla backend',
    'settings.refreshLogs': 'Aggiorna log',
    'settings.copyDiagnostics': 'Copia diagnostica',
    'settings.copied': 'Copiato.',
    'settings.backendStatus': 'Stato backend:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'controllo',
    'settings.appVersion': 'Versione app',

    // Languages
    'lang.en': 'Inglese',
    'lang.it': 'Italiano',
    'lang.fr': 'Francese',
    'lang.de': 'Tedesco',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.dashboard': 'Tableau de bord',
    'nav.chat': 'Chat',
    'nav.compare': 'Comparer',
    'nav.database': 'Base de données',
    'nav.reports': 'Rapports',
    'nav.settings': 'Paramètres',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.close': 'Fermer',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.sort': 'Trier',
    'common.reset': 'Réinitialiser',
    'common.reviews': 'Avis',
    'common.games': 'Jeux',
    'common.filters': 'Filtres',
    'common.all': 'Tous',
    'common.recommended': 'Recommandé',
    'common.notRecommended': 'Non recommandé',
    'common.issues': 'Problèmes',
    'common.requests': 'Demandes',
    'common.evidence': 'Preuves',
    'common.labels': 'Étiquettes',
    'common.noData': 'Aucune donnée',

    // Dashboard
    'dashboard.title': 'Tableau de bord',
    'dashboard.analyze': 'Analyser',
    'dashboard.analyzing': 'Analyse...',
    'dashboard.noGames': 'Aucun jeu analysé',
    'dashboard.recommendation': 'Recommandation',
    'dashboard.issueRate': 'Taux de problèmes',
    'dashboard.requestRate': 'Taux de demandes',
    'dashboard.welcome': 'Bienvenue',
    'dashboard.welcomeTo': 'Bienvenue sur SentiNext',
    'dashboard.subtitle': 'Comprenez ce que les joueurs pensent vraiment. Commencez une nouvelle analyse Steam ou revenez à un rapport récent.',
    'dashboard.newAnalysis': 'Nouvelle analyse de jeu',
    'dashboard.newAnalysisDesc': 'Recherchez Steam pour commencer une nouvelle classification d\'avis.',
    'dashboard.searchPlaceholder': 'Rechercher un jeu (ex. Baldur\'s Gate 3)',
    'dashboard.searching': 'Recherche...',
    'dashboard.noGamesFound': 'Aucun jeu trouvé. Essayez un autre terme.',
    'dashboard.recentAnalyses': 'Analyses récentes',
    'dashboard.recentDesc': 'Ouvrez un tableau de bord sauvegardé de vos dernières exécutions.',
    'dashboard.viewAll': 'Tout voir',
    'dashboard.noAnalyses': 'Aucune analyse',
    'dashboard.noAnalysesDesc': 'Recherchez un jeu pour commencer votre première analyse.',
    'dashboard.openReviews': 'Ouvrir les avis',
    'dashboard.filtersActive': 'Actifs',
    'dashboard.showFilters': 'Afficher les filtres',
    'dashboard.hideFilters': 'Masquer les filtres',
    'dashboard.categoriesOverview': 'Aperçu des catégories',
    'dashboard.topIssues': 'Principaux problèmes',
    'dashboard.topRequests': 'Principales demandes',
    'dashboard.newSearch': 'Nouvelle Recherche',

    // Chat
    'chat.title': 'Assistant IA',
    'chat.subtitle': 'Votre partenaire conversationnel intelligent',
    'chat.placeholder': 'Tapez votre message...',
    'chat.send': 'Envoyer',
    'chat.newChat': 'Nouveau Chat',
    'chat.history': 'Historique des chats',
    'chat.context': 'Contexte',
    'chat.noConversations': 'Aucune conversation',
    'chat.selectGames': 'Sélectionnez jusqu\'à 2 jeux pour rechercher des avis:',
    'chat.clearSelection': 'Effacer la sélection',
    'chat.noStarredGames': 'Aucun jeu favori',
    'chat.loadingGames': 'Chargement des jeux...',
    'chat.chatWithData': 'Discuter avec Vos Données',
    'chat.startConversation': 'Démarrer une conversation',
    'chat.askAnything': 'Demandez-moi n\'importe quoi!',
    'chat.sources': 'Sources',

    // Compare
    'compare.title': 'Comparaison de jeux',
    'compare.selectGames': 'Sélectionnez au moins 2 jeux',
    'compare.categoryOverview': 'Aperçu des catégories',
    'compare.categoryRecommendation': 'Recommandation par catégorie',
    'compare.sortBy': 'Trier par:',
    'compare.biggestDiff': 'Plus grande différence',
    'compare.highestRating': 'Note la plus élevée',
    'compare.lowestRating': 'Note la plus basse',
    'compare.mostReviews': 'Plus d\'avis',
    'compare.onlySignificant': 'Afficher uniquement les différences significatives (>10%)',
    'compare.resetFilters': 'Réinitialiser les filtres',
    'compare.sampleReviews': 'Exemples d\'avis',
    'compare.exampleReviews': 'Exemples d\'avis de chaque jeu pour cette sous-catégorie',
    'compare.noGames': 'Aucun jeu à comparer',
    'compare.analyzeFirst': 'Analysez d\'abord des jeux pour les comparer ici.',
    'compare.selectGamesDesc': 'Sélectionner des jeux',
    'compare.selected': 'Sélectionnés',
    'compare.visualComparison': 'Comparaison visuelle de toutes les catégories',

    // Database
    'database.title': 'Explorateur de base de données',
    'database.subtitle': 'Parcourez tous les avis stockés.',
    'database.myData': 'Mes données',
    'database.allUsers': 'Tous les utilisateurs',
    'database.stats': 'Statistiques de la base de données',
    'database.loadingStats': 'Chargement des statistiques...',
    'database.games': 'Jeux',
    'database.reviews': 'Avis',
    'database.starred': 'Favoris',
    'database.labels': 'Étiquettes',
    'database.noData': 'Aucune donnée locale',
    'database.noDataDesc': 'Effectuez votre première analyse pour remplir la base de données.',
    'database.filters': 'Filtres de dataset',
    'database.filtersDesc': 'Rechercher et filtrer dans toute la base de données.',
    'database.searchText': 'Rechercher du texte',
    'database.searchPlaceholder': 'Rechercher le texte d\'avis',
    'database.game': 'Jeu',
    'database.allGames': 'Tous les jeux',
    'database.language': 'Langue',
    'database.category': 'Catégorie',
    'database.allCategories': 'Toutes les catégories',
    'database.subcategory': 'Sous-catégorie',
    'database.allSubcategories': 'Toutes les sous-catégories',
    'database.quickFilters': 'Filtres rapides',
    'database.allSentiment': 'Tous les sentiments',
    'database.allLabels': 'Toutes les étiquettes',
    'database.downloadCSV': 'Télécharger CSV',
    'database.downloadJSON': 'Télécharger JSONL',
    'database.noReviews': 'Aucun avis ne correspond à ces filtres.',
    'database.reviewDetails': 'Détails de l\'avis',

    // Settings
    'settings.title': 'Paramètres',
    'settings.subtitle': 'Compte, stockage et diagnostics pour ce service.',
    'settings.language': 'Langue',
    'settings.selectLanguage': 'Sélectionnez votre langue préférée',
    'settings.appearance': 'Apparence',
    'settings.notifications': 'Notifications',
    'settings.account': 'Compte',
    'settings.accountDesc': 'Gérez votre session et déconnectez-vous.',
    'settings.diagnostics': 'Diagnostics',
    'settings.diagnosticsDesc': 'Utilisez ceci lorsque le backend est lent ou ne répond pas.',
    'settings.recheckBackend': 'Revérifier le backend',
    'settings.refreshLogs': 'Actualiser les journaux',
    'settings.copyDiagnostics': 'Copier les diagnostics',
    'settings.copied': 'Copié.',
    'settings.backendStatus': 'État du backend:',
    'settings.online': 'en ligne',
    'settings.offline': 'hors ligne',
    'settings.checking': 'vérification',
    'settings.appVersion': 'Version de l\'app',

    // Languages
    'lang.en': 'Anglais',
    'lang.it': 'Italien',
    'lang.fr': 'Français',
    'lang.de': 'Allemand',
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.dashboard': 'Dashboard',
    'nav.chat': 'Chat',
    'nav.compare': 'Vergleichen',
    'nav.database': 'Datenbank',
    'nav.reports': 'Berichte',
    'nav.settings': 'Einstellungen',

    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.close': 'Schließen',
    'common.search': 'Suchen',
    'common.filter': 'Filtern',
    'common.sort': 'Sortieren',
    'common.reset': 'Zurücksetzen',
    'common.reviews': 'Bewertungen',
    'common.games': 'Spiele',
    'common.filters': 'Filter',
    'common.all': 'Alle',
    'common.recommended': 'Empfohlen',
    'common.notRecommended': 'Nicht empfohlen',
    'common.issues': 'Probleme',
    'common.requests': 'Anfragen',
    'common.evidence': 'Beweise',
    'common.labels': 'Etiketten',
    'common.noData': 'Keine Daten',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.analyze': 'Analysieren',
    'dashboard.analyzing': 'Analysiere...',
    'dashboard.noGames': 'Noch keine Spiele analysiert',
    'dashboard.recommendation': 'Empfehlung',
    'dashboard.issueRate': 'Problem-Rate',
    'dashboard.requestRate': 'Anfrage-Rate',
    'dashboard.welcome': 'Willkommen',
    'dashboard.welcomeTo': 'Willkommen bei SentiNext',
    'dashboard.subtitle': 'Verstehen Sie, was Spieler wirklich denken. Starten Sie eine neue Steam-Analyse oder kehren Sie zu einem kürzlichen Bericht zurück.',
    'dashboard.newAnalysis': 'Neue Spielanalyse',
    'dashboard.newAnalysisDesc': 'Suchen Sie auf Steam, um eine neue Bewertungsklassifizierung zu beginnen.',
    'dashboard.searchPlaceholder': 'Nach einem Spiel suchen (z.B. Baldur\'s Gate 3)',
    'dashboard.searching': 'Suche...',
    'dashboard.noGamesFound': 'Keine Spiele gefunden. Versuchen Sie einen anderen Suchbegriff.',
    'dashboard.recentAnalyses': 'Letzte Analysen',
    'dashboard.recentDesc': 'Öffnen Sie ein gespeichertes Dashboard aus Ihren letzten Läufen.',
    'dashboard.viewAll': 'Alle anzeigen',
    'dashboard.noAnalyses': 'Noch keine Analysen',
    'dashboard.noAnalysesDesc': 'Suchen Sie nach einem Spiel, um Ihre erste Analyse zu starten.',
    'dashboard.openReviews': 'Bewertungen öffnen',
    'dashboard.filtersActive': 'Aktiv',
    'dashboard.showFilters': 'Filter anzeigen',
    'dashboard.hideFilters': 'Filter ausblenden',
    'dashboard.categoriesOverview': 'Kategorieübersicht',
    'dashboard.topIssues': 'Hauptprobleme',
    'dashboard.topRequests': 'Hauptanfragen',
    'dashboard.newSearch': 'Neue Suche',

    // Chat
    'chat.title': 'KI-Assistent',
    'chat.subtitle': 'Ihr intelligenter Gesprächspartner',
    'chat.placeholder': 'Geben Sie Ihre Nachricht ein...',
    'chat.send': 'Senden',
    'chat.newChat': 'Neuer Chat',
    'chat.history': 'Chat-Verlauf',
    'chat.context': 'Kontext',
    'chat.noConversations': 'Noch keine Gespräche',
    'chat.selectGames': 'Wählen Sie bis zu 2 Spiele aus, um Bewertungen zu durchsuchen:',
    'chat.clearSelection': 'Auswahl löschen',
    'chat.noStarredGames': 'Keine Lieblingsspiele',
    'chat.loadingGames': 'Spiele laden...',
    'chat.chatWithData': 'Mit Ihren Daten chatten',
    'chat.startConversation': 'Gespräch beginnen',
    'chat.askAnything': 'Fragen Sie mich alles!',
    'chat.sources': 'Quellen',

    // Compare
    'compare.title': 'Spielevergleich',
    'compare.selectGames': 'Wählen Sie mindestens 2 Spiele',
    'compare.categoryOverview': 'Kategorieübersicht',
    'compare.categoryRecommendation': 'Kategorieempfehlung',
    'compare.sortBy': 'Sortieren nach:',
    'compare.biggestDiff': 'Größter Unterschied',
    'compare.highestRating': 'Höchste Bewertung',
    'compare.lowestRating': 'Niedrigste Bewertung',
    'compare.mostReviews': 'Meiste Bewertungen',
    'compare.onlySignificant': 'Nur signifikante Unterschiede anzeigen (>10%)',
    'compare.resetFilters': 'Filter zurücksetzen',
    'compare.sampleReviews': 'Beispielbewertungen',
    'compare.exampleReviews': 'Beispielbewertungen von jedem Spiel für diese Unterkategorie',
    'compare.noGames': 'Keine Spiele zum Vergleichen',
    'compare.analyzeFirst': 'Analysieren Sie zuerst einige Spiele, um sie hier zu vergleichen.',
    'compare.selectGamesDesc': 'Spiele auswählen',
    'compare.selected': 'Ausgewählt',
    'compare.visualComparison': 'Visueller Vergleich aller Kategorien',

    // Database
    'database.title': 'Datenbank-Explorer',
    'database.subtitle': 'Durchsuchen Sie alle gespeicherten Bewertungen.',
    'database.myData': 'Meine Daten',
    'database.allUsers': 'Alle Benutzer',
    'database.stats': 'Datenbankstatistiken',
    'database.loadingStats': 'Statistiken laden...',
    'database.games': 'Spiele',
    'database.reviews': 'Bewertungen',
    'database.starred': 'Favoriten',
    'database.labels': 'Etiketten',
    'database.noData': 'Keine lokalen Daten',
    'database.noDataDesc': 'Führen Sie Ihre erste Analyse durch, um die Datenbank zu füllen.',
    'database.filters': 'Dataset-Filter',
    'database.filtersDesc': 'Durchsuchen und filtern Sie die gesamte Datenbank.',
    'database.searchText': 'Text suchen',
    'database.searchPlaceholder': 'Bewertungstext suchen',
    'database.game': 'Spiel',
    'database.allGames': 'Alle Spiele',
    'database.language': 'Sprache',
    'database.category': 'Kategorie',
    'database.allCategories': 'Alle Kategorien',
    'database.subcategory': 'Unterkategorie',
    'database.allSubcategories': 'Alle Unterkategorien',
    'database.quickFilters': 'Schnellfilter',
    'database.allSentiment': 'Alle Stimmungen',
    'database.allLabels': 'Alle Etiketten',
    'database.downloadCSV': 'CSV herunterladen',
    'database.downloadJSON': 'JSONL herunterladen',
    'database.noReviews': 'Keine Bewertungen entsprechen diesen Filtern.',
    'database.reviewDetails': 'Bewertungsdetails',

    // Settings
    'settings.title': 'Einstellungen',
    'settings.subtitle': 'Konto, Speicher und Diagnose für diesen Dienst.',
    'settings.language': 'Sprache',
    'settings.selectLanguage': 'Wählen Sie Ihre bevorzugte Sprache',
    'settings.appearance': 'Erscheinungsbild',
    'settings.notifications': 'Benachrichtigungen',
    'settings.account': 'Konto',
    'settings.accountDesc': 'Verwalten Sie Ihre Sitzung und melden Sie sich ab.',
    'settings.diagnostics': 'Diagnose',
    'settings.diagnosticsDesc': 'Verwenden Sie dies, wenn das Backend langsam ist oder nicht reagiert.',
    'settings.recheckBackend': 'Backend erneut prüfen',
    'settings.refreshLogs': 'Protokolle aktualisieren',
    'settings.copyDiagnostics': 'Diagnose kopieren',
    'settings.copied': 'Kopiert.',
    'settings.backendStatus': 'Backend-Status:',
    'settings.online': 'online',
    'settings.offline': 'offline',
    'settings.checking': 'prüfen',
    'settings.appVersion': 'App-Version',

    // Languages
    'lang.en': 'Englisch',
    'lang.it': 'Italienisch',
    'lang.fr': 'Französisch',
    'lang.de': 'Deutsch',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const saved = localStorage.getItem('senti-next-language') as Language;
    if (saved && ['en', 'it', 'fr', 'de'].includes(saved)) {
      setLanguageState(saved);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('senti-next-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
