'use client';

import { createContext, useContext, ReactNode } from 'react';

interface LanguageContextType {
  language: 'en';
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations: Record<string, string> = {
  // Navigation
  'nav.home': 'Home',
  'nav.dashboard': 'Dashboard',
  'nav.chat': 'Chat with Agent',
  'nav.chatMobile': 'Agent',
  'nav.compare': 'Compare',
  'nav.database': 'Database',
  'nav.reports': 'Reports',
  'nav.support': 'Support',
  'nav.inbox': 'Inbox',
  'nav.settings': 'Settings',

  // Common
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.close': 'Close',
  'common.search': 'Search',
  'common.filter': 'Filter',
  'common.sort': 'Sort',
  'common.reset': 'Reset',
  'common.apply': 'Apply',
  'common.calculate': 'Calculate',
  'common.refresh': 'Refresh',
  'common.clearFilters': 'Clear filters',
  'common.pending': 'Pending',
  'common.dismiss': 'Dismiss',
  'common.reviews': 'Reviews',
  'common.games': 'Games',
  'common.languages': 'Languages',
  'common.filters': 'Filters',
  'common.all': 'All',
  'common.recommended': 'Recommended',
  'common.notRecommended': 'Not recommended',
  'common.issues': 'Issues',
  'common.requests': 'Requests',
  'common.evidence': 'Evidence',
  'common.labels': 'Labels',
  'common.noData': 'No data',

  // Filters
  'filters.allSentiment': 'All',
  'filters.allTime': 'All time',
  'filters.last30Days': 'Last 30 days',
  'filters.last90Days': 'Last 90 days',
  'filters.last12Months': 'Last 12 months',
  'filters.customRange': 'Custom range',
  'filters.allHelpful': 'All helpful',
  'filters.helpfulVotes10': '10+ votes',
  'filters.helpfulVotes25': '25+ votes',
  'filters.helpfulVotes50': '50+ votes',
  'filters.allPlaytime': 'All playtime',
  'filters.playtimeLt2h': '<2h playtime',
  'filters.playtime2to20h': '2–20h playtime',
  'filters.playtime20hplus': '20h+ playtime',
  'filters.helpfulVotes': '{count}+ helpful',
  'filters.languageChip': 'Lang: {lang}',

  // Game Context
  'gameContext.currentGame': 'Current game',
  'gameContext.noGame': 'No game',
  'gameContext.noSavedGames': 'No saved games',
  'gameContext.analyzeNew': 'Analyze new game',
  'gameContext.filteredReviews': 'Filtered reviews: {filtered} / {total}',
  'gameContext.sampledReviews': 'Sampled reviews: {total}',
  'gameContext.filtersApply': 'Filters apply to your current game reviews.',
  'gameContext.selectGameHint': 'Select a game to see review totals.',
  'gameContext.analyzeToSeeReviews': 'Analyze this game to see review totals.',
  'gameContext.activeFilters': 'Active filters:',
  'gameContext.noFiltersActive': 'No filters active',

  // Dashboard
  'dashboard.title': 'Dashboard',
  'dashboard.analyze': 'Analyze',
  'dashboard.update': 'Refresh latest 1,000 reviews',
  'dashboard.analyzing': 'Analyzing...',
  'dashboard.noGames': 'No games analyzed yet',
  'dashboard.recommendation': 'Recommendation',
  'dashboard.issueRate': 'Issue rate',
  'dashboard.requestRate': 'Request rate',
  'dashboard.welcome': 'Welcome',
  'dashboard.welcomeTo': 'Welcome to SENTINEXT',
  'dashboard.subtitle': 'Understand what players really think. Start with a new Steam analysis or jump back into a recent report.',
  'dashboard.newAnalysis': 'New game analysis',
  'dashboard.newAnalysisDesc': 'Search Steam to begin a fresh review classification run.',
  'dashboard.searchPlaceholder': 'Search for a game (e.g., Baldur\'s Gate 3)',
  'dashboard.searching': 'Searching...',
  'dashboard.noGamesFound': 'No games found. Try a different search term.',
  'dashboard.recentAnalyses': 'Recent analyses',
  'dashboard.recentDesc': 'Open a saved dashboard from your latest runs.',
  'dashboard.viewAll': 'View all',
  'dashboard.noAnalyses': 'No analyses yet',
  'dashboard.noAnalysesDesc': 'Search for a game to start your first analysis.',
  'dashboard.openReviews': 'Open reviews',
  'dashboard.filtersActive': 'Active',
  'dashboard.showFilters': 'Show all filters',
  'dashboard.hideFilters': 'Hide all filters',
  'dashboard.lastMonthOnly': 'Last 30 days',
  'dashboard.categoriesOverview': 'Categories overview',
  'dashboard.topIssues': 'Top issues',
  'dashboard.topRequests': 'Top feature requests',
  'dashboard.newSearch': 'New Search',
  'dashboard.settings': 'Settings',
  'dashboard.costPreview': 'Cost Preview',
  'dashboard.calculating': 'Calculating...',
  'dashboard.costPreviewHint': 'Click Calculate to preview credits, cache reuse, and ETA.',
  'dashboard.processing': 'Processing',
  'dashboard.newReviews': 'New reviews',
  'dashboard.cached': 'Cached',
  'dashboard.cacheReuse': 'Cache reuse',
  'dashboard.etaRough': 'ETA (rough)',
  'dashboard.llmCalls': 'LLM calls',
  'dashboard.creditsLabel': 'Credits',
  'dashboard.costLabel': 'Cost',
  'dashboard.balanceLabel': 'Balance',
  'dashboard.creditStatusInsufficient': 'Insufficient',
  'dashboard.creditStatusOverLimit': 'Over limit',
  'dashboard.creditStatusOk': 'OK',
  'dashboard.creditWarningHard': 'Insufficient credits. Upgrade your plan or reduce reviews.',
  'dashboard.creditWarningSoft': 'This will exceed your monthly limit but you can still proceed.',
  'dashboard.queueRunning': 'Analysis running • {count} in queue',
  'dashboard.queueStatus': 'Queue: {count} running',

  // Chat
  'chat.title': 'Chat with Agent',
  'chat.subtitle': 'Your intelligent conversation partner',
  'chat.placeholder': 'Type your message...',
  'chat.send': 'Send',
  'chat.newChat': 'New Chat',
  'chat.history': 'Chat History',
  'chat.context': 'Context',
  'chat.noConversations': 'No conversations yet',
  'chat.selectGames': 'Select up to 2 games to search reviews:',
  'chat.clearSelection': 'Clear selection',
  'chat.noStarredGames': 'No starred games yet',
  'chat.loadingGames': 'Loading games...',
  'chat.chatWithData': 'Chat with Your Data',
  'chat.startConversation': 'Start a conversation',
  'chat.askAnything': 'Ask me anything!',
  'chat.sources': 'Sources',
  'chat.sourcesUsed': 'Sources used',
  'chat.showSources': 'Show sources',
  'chat.hideSources': 'Hide sources',
  'chat.promptPresets': 'Prompt presets',
  'chat.selectGameNotice': 'Select a game to run this prompt.',
  'chat.copySuccess': 'Answer copied',
  'chat.copyFailed': 'Copy failed',
  'chat.copy': 'Copy',
  'chat.regenerate': 'Regenerate',
  'chat.suggestedQuestions': 'Suggested questions',
  'chat.pleaseClarify': 'Please clarify',
  'chat.selectGame': 'Select a game',
  'chat.searchFor': 'Search for {game}',
  'chat.searchForGames': 'Search for games',
  'chat.loadingConversation': 'Loading conversation...',

  // Compare
  'compare.title': 'Game Comparison',
  'compare.selectGames': 'Select at least 2 games',
  'compare.categoryOverview': 'Category Overview',
  'compare.categoryRecommendation': 'Category recommendation',
  'compare.sortBy': 'Sort by:',
  'compare.biggestDiff': 'Biggest Difference',
  'compare.highestRating': 'Highest Rating',
  'compare.lowestRating': 'Lowest Rating',
  'compare.mostReviews': 'Most Reviews',
  'compare.onlySignificant': 'Only show significant differences (>10%)',
  'compare.resetFilters': 'Reset filters',
  'compare.sampleReviews': 'Sample Reviews',
  'compare.exampleReviews': 'Example reviews from each game for this subcategory',
  'compare.noGames': 'No games to compare',
  'compare.analyzeFirst': 'Analyze some games first to compare them here.',
  'compare.selectGamesDesc': 'Select Games',
  'compare.selected': 'Selected',
  'compare.visualComparison': 'Visual comparison across all categories',
  'compare.swapPrompt': 'Only 2 games can be compared. Swap in {game}?',
  'compare.swapHint': 'Choose a game to replace.',
  'compare.swapReplace': 'Replace {game}',

  // Database
  'database.title': 'Database Explorer',
  'database.subtitle': 'Browse every stored review across all accounts.',
  'database.myData': 'My data',
  'database.allUsers': 'All users',
  'database.stats': 'Database statistics',
  'database.loadingStats': 'Loading stats...',
  'database.games': 'Games',
  'database.reviews': 'Reviews',
  'database.starred': 'Starred',
  'database.labels': 'Labels',
  'database.noData': 'No local data yet',
  'database.noDataDesc': 'Run your first analysis to populate the database.',
  'database.filters': 'Dataset filters',
  'database.filtersDesc': 'Search and filter across the entire database.',
  'database.searchText': 'Search text',
  'database.searchPlaceholder': 'Search review text',
  'database.game': 'Game',
  'database.allGames': 'All games',
  'database.language': 'Language',
  'database.category': 'Category',
  'database.allCategories': 'All categories',
  'database.subcategory': 'Subcategory',
  'database.allSubcategories': 'All subcategories',
  'database.quickFilters': 'Quick filters',
  'database.allSentiment': 'All',
  'database.allLabels': 'All labels',
  'database.downloadCSV': 'Download CSV',
  'database.downloadJSON': 'Download JSONL',
  'database.noReviews': 'No reviews match these filters.',
  'database.reviewDetails': 'Review details',
  'database.categories': 'Categories',
  'database.metadata': 'Metadata',
  'database.export': 'Export',
  'database.sentiment': 'Recommendation',
  'database.type': 'Type',
  'database.previewExport': 'Preview export',
  'database.preparingExport': 'Preparing…',
  'database.applyFilters': 'Apply filters',
  'database.scope': 'Scope',

  // Settings
  'settings.title': 'Settings',
  'settings.subtitle': 'Account, storage, and diagnostics for this service.',
  'settings.appearance': 'Appearance',
  'settings.notifications': 'Notifications',
  'settings.account': 'Account',
  'settings.accountDesc': 'Manage your session and sign out.',
  'settings.diagnostics': 'Diagnostics',
  'settings.diagnosticsDesc': 'Use this when the backend is slow or unresponsive.',
  'settings.recheckBackend': 'Recheck backend',
  'settings.refreshLogs': 'Refresh logs',
  'settings.copyDiagnostics': 'Copy diagnostics',
  'settings.copied': 'Copied.',
  'settings.backendStatus': 'Backend status:',
  'settings.online': 'online',
  'settings.offline': 'offline',
  'settings.checking': 'checking',
  'settings.appVersion': 'App version',

  // Onboarding
  'onboarding.welcome': 'Welcome to SENTINEXT',
  'onboarding.welcomeDesc': 'Understand what players really think about any Steam game with AI-powered review analysis.',
  'onboarding.step1.title': 'Search & Analyze',
  'onboarding.step1.desc': 'Search for any Steam game and analyze up to 1,000 reviews with our AI classification system.',
  'onboarding.step2.title': 'Insights Dashboard',
  'onboarding.step2.desc': 'Get KPIs, recommendation trends, player segmentation, and category breakdowns at a glance.',
  'onboarding.step3.title': 'AI-Powered Features',
  'onboarding.step3.desc': 'Chat with an AI agent, generate summaries, and compare games side by side.',
  'onboarding.skip': 'Skip',
  'onboarding.back': 'Back',
  'onboarding.next': 'Next',
  'onboarding.getStarted': 'Get Started',
  'onboarding.feature.chat': 'Chat Agent',
  'onboarding.feature.chatDesc': 'Ask questions about player feedback',
  'onboarding.feature.summary': 'AI Summaries',
  'onboarding.feature.summaryDesc': 'Get instant insights from reviews',
  'onboarding.feature.compare': 'Compare Games',
  'onboarding.feature.compareDesc': 'Benchmark against competitors',

  // Onboarding - stat labels
  'onboarding.stat.reviewsAnalyzed': 'Reviews Analyzed',
  'onboarding.stat.aiCategories': 'AI Categories',
  'onboarding.stat.languages': 'Languages',

  // Onboarding - Step 2 section headers
  'onboarding.step2.keyMetrics': 'Key Metrics',
  'onboarding.step2.sentimentTrend': 'Recommendation Trend',
  'onboarding.step2.categoryBreakdown': 'Category Breakdown',

  // Onboarding - Step 4 (Pricing)
  'onboarding.step4.title': 'Plans & Pricing',
  'onboarding.step4.desc': 'Start free and scale as you grow. Every plan includes AI classification, chat, and summaries.',

  // Onboarding - Tier labels
  'onboarding.tier.free': 'Free',
  'onboarding.tier.indie': 'Indie',
  'onboarding.tier.pro': 'Pro', // deprecated — kept for backward compat
  'onboarding.tier.enterprise': 'Enterprise',
  'onboarding.tier.perMonth': 'mo',
  'onboarding.tier.custom': 'Custom',
  'onboarding.tier.unlimited': 'Unlimited',
  'onboarding.tier.popular': 'Popular',
  'onboarding.tier.creditsLabel': 'Credits',
  'onboarding.tier.trialCredits': 'One-time trial credits',
  'onboarding.tier.indieCredits': '5,000/mo',
  'onboarding.tier.proCredits': '15,000/mo',
  'onboarding.tier.creditCosts': 'Credit Costs',
  'onboarding.tier.classifyCost': 'Classify: 1 credit',
  'onboarding.tier.chatCost': 'Chat: 2 credits',
  'onboarding.tier.summaryCost': 'Summary: 1 credit',
  'onboarding.tier.includes': 'Includes',
  'onboarding.tier.subscribe': 'Subscribe',
  'onboarding.tier.tryFree': 'Try for Free',
  'onboarding.tier.contactUs': 'Contact Us',
  'upgrade.banner': 'Upgrade your plan',
  'upgrade.unlockMore': 'Get more credits and unlock full potential',
};

const t = (key: string): string => {
  return translations[key] || key;
};

const contextValue: LanguageContextType = {
  language: 'en',
  setLanguage: () => {},
  t,
};

const LanguageContext = createContext<LanguageContextType>(contextValue);

export function LanguageProvider({ children }: { children: ReactNode }) {
  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
